cozy/cozy-home

- app/containers/ConnectorManagement.jsx
- app/index.jsx
- app/initKonnectors.json
- app/lib/MyAccountsStore.js
- app/locales/en.json
- vendor/assets/manifest.webapp
Work in progress for installing and displaying a connector. Still some things to do :
Prerequisite : the my account application needs to have the slug "settings" to be able to install konnectors (waiting for a fix in the cozy-stack)
> WIP : Install the chosen connector

- app/containers/ConnectorManagement.jsx
- app/styles/index.styl
> feat: Made a cleaner installing konnector view

- app/containers/ConnectorManagement.jsx
- app/index.jsx
- app/lib/MyAccountsStore.js
Ping @lespacedunmatin que je n'arrive pas à assigner en reviewer :(
> feat: handle error on connector installation

- app/contexts/cozy/index.json
Use cases content displaying failed due to non-existing konnectors in the use cases manifest. Fixed.
> feat: remove not yet existing konnectors from use cases

- app/lib/MyAccountsStore.js
- app/lib/konnectors.js
This error was due to a setTimeout to 120ms
> fix: First installation error

- app/lib/MyAccountsStore.js
- app/lib/konnectors.js
- vendor/assets/manifest.webapp
> feat: now run the konnector on submit

- app/styles/dialog.styl
The copy/pasted code wasn't correctly indented.
> Minor fix dialog header styles

- src/styles/dialog.styl
- src/styles/sidebar.styl
Avoid styles conflits with the cozy-bar.
> Make some global css rules more specific to the application

- src/initKonnectors.json
- src/lib/konnectors.js
Last fixes for previous PR #43
> Last fixes for previous PR #43

- manifest.webapp
- src/components/AccountManagement.jsx
- src/containers/ConnectorManagement.jsx
- src/lib/DataConnectStore.js
- src/lib/accounts.js
- src/lib/konnectors.js
@gregorylegarec just to let you know
> feat: account deletion

- package.json
- src/components/UseCaseDialog.jsx
- src/styles/lists.styl
- yarn.lock
Needs merge in cozy UI :
* https://github.com/cozy/cozy-ui/pull/104
* https://github.com/cozy/cozy-ui/pull/103
> feat: update use case UI

- src/containers/ConnectorManagement.jsx
- src/lib/konnectors.js
- src/locales/en.json
Still waiting for the cozy-stack side at the moment
> WIP: feat: Manage errors coming from the connector

- src/contexts/cozy/index.json
- src/initKonnectors.json
- src/locales/en.json
This PR :   
* Change MAIF category from 'health' to 'insurance'
*Remove useless use cases : contacts and agenda.
> Change MAIF category and remove useless use cases.

- src/contexts/cozy/index.json
> Add sosh and freemobile in phone use case

- src/components/AccountConnection.jsx
- src/components/AccountLoginForm.jsx
- src/components/Field.jsx
- src/containers/ConnectorManagement.jsx
- src/lib/accounts.js
- src/styles/field.styl
Based on https://github.com/cozy/cozy-collect/pull/71.
Please consider only commit https://github.com/cozy/cozy-collect/pull/76/commits/74f71f7a2d33a60c84b19fb35b5028f713da4e37.
> feat: credentials errors in login form

- config/webpack.config.dev.js
- config/webpack.config.prod.js
- src/index.jsx
Same as this one : https://github.com/cozy/cozy-settings/pull/50
> feat: track user by id and app

- src/components/services/CreateAccountService.jsx
- src/containers/ConnectorManagement.jsx
- src/containers/IntentService.jsx
- src/lib/popup.js
I just separated the popup handling code at the moment and the orange vod konnector should work in interapp
when orange api is back.
I did not manage to refactor the rest of the code at the moment.
> [WIP] feat added OAuth in interapp service

- src/components/AccountLoginForm.jsx
Following https://github.com/cozy/cozy-ui/pull/120.
> feat: add spinner on delete account button

- src/contexts/cozy/index.json
- src/initKonnectors.json
> Rename Orange VOD to Orange Livebox

- src/styles/services.styl
fixes https://github.com/cozy/cozy-collect/issues/109
> fix: remove overflow-y causing ugly scrollbar to appear

- src/containers/AccountConnection.jsx
- src/containers/ConnectorManagement.jsx
- src/lib/CollectStore.js
Now update the state of the konnector in memory after it has been run
> fix: display good state icon when coming back from the modale

- src/styles/accountConnection.styl
I think the modal styles can really be improved for better responsive, but it's not the goal of this PR.
> Fit connection modal for mobile

- config/webpack.config.base.js
- src/lib/accounts.js
- src/locales/en.json
- src/styles/sidebar.styl
The main app was importing duplicated `app.js` and `app.css` files which cause some errors with duplicated styles and JS requests. This PR fixe that and brings some little improvements.
> Improvements

- src/containers/App.jsx
- src/index.jsx
Maybe we should go further by creating a dedicated route. A lot of thing are loaded on this page for relatively small script.
> refactor: handle OAuth early :art:

- src/components/AccountLoginForm.jsx
- src/components/Field.jsx
This fixes chrome behavior to not mix saved accounts logins in the account form
> fix: added autocomplete attribute to account fields

- src/components/AccountLoginForm.jsx
- src/components/CategoryList.jsx
- src/components/ConnectedList.jsx
- src/components/ConnectorList.jsx
- src/components/DiscoveryList.jsx
- src/components/Failure.jsx
- src/components/Loading.jsx
- src/components/Sidebar.jsx
- src/containers/AccountConnection.jsx
- src/containers/ConnectorManagement.jsx
- src/containers/IntentService.jsx
- src/locales/en.json
Stop keeping legacy locales which prone duplications.
Should be merged ASAP.
> Refactor locales structure :fire:

- src/components/AccountLoginForm.jsx
- src/components/DescriptionContent.jsx
- src/containers/AccountConnection.jsx
- src/containers/ConnectorManagement.jsx
- src/lib/accounts.js
- src/lib/konnectors.js
- src/locales/en.json
- src/styles/accountConnection.styl
- src/styles/accountLoginForm.styl
* Clean-up message system to improve it using only AccountConnection modal
* Display folderPath instead of folderID
* Fix bug about getting back to the config after a success
* Some minor changes
> Improve messages system + clean-up

- src/containers/AccountConnection.jsx
- src/lib/CollectStore.js
- src/lib/konnectors.js
> Better handling success time out

- src/containers/AccountConnection.jsx
- src/containers/IntentService.jsx
- src/lib/CollectStore.js
- src/lib/konnectors.js
This feature allows to create an intent with a successTimeout of 20 sec, if you send to the Intend a `timeout = true` into the data.
> feat: have an option in intentService to enforce SuccessTimeout

- src/lib/CollectStore.js
This caused the execution by trigger to not work at all
> fix: now pass correctly the folder id to the trigger

- src/components/services/CreateAccountService.jsx
- src/containers/AccountConnection.jsx
* Remove onSubmit in CreatAccountService not used anymore
* Remove timeout error exception not used anymore
* Connect onError and onSuccess Service handling functions to AccountConnection
> Minor fixes

- src/containers/ConnectorManagement.jsx
- src/styles/connectorManagement.styl
- src/styles/index.styl
Hope this time is the right time… at least for this time… again…
> CC-13 | And we make the towels turn

- src/containers/ConnectorManagement.jsx
- src/plugins/i18n.js
- src/styles/connectorManagement.styl
- src/styles/index.styl
> fix: spinner issue :ambulance:

- src/components/AccountLoginForm.jsx
- src/components/FixedProgress.jsx
- src/styles/accountLoginForm.styl
- src/styles/fixedProgress.styl
> feat: improve progress bar UI :lipstick:

- src/styles/fixedProgress.styl
I used `grey-01` as `pale-grey` does not provide the expected color.
> fix: linting :ambulance:

- src/components/AccountLoginForm.jsx
- src/containers/AccountConnection.jsx
- src/containers/ConnectorManagement.jsx
- src/styles/accountLoginForm.styl
> Fix saved login password (recover)

- src/config/categories.json
- src/containers/App.jsx
- src/containers/ConnectorManagement.jsx
- src/lib/CollectStore.js
Better handling connectors categories with an authorized array similar to datatypes handling.
If we can merge this PR quickly, I'll need it for #194
> Better handling authorized connectors categories

- src/components/CategoryList.jsx
- src/components/ConnectedList.jsx
- src/components/ConnectorItem.jsx
- src/components/ConnectorList.jsx
- src/components/KonnectorItem.jsx
- src/components/KonnectorList.jsx
- src/components/UseCaseDialog.jsx
- src/components/UseCaseItem.jsx
- src/components/UseCaseList.jsx
- src/containers/ConnectorManagement.jsx
- src/contexts/cozy/locales/en.json
- src/lib/CollectStore.js
Prepare realtime implementation by simplifying `KonnectorItem` component.
> refacto: little refactoring before realtime :art:

- src/components/KonnectorSuccess.jsx
- src/containers/AccountConnection.jsx
- src/styles/konnectorSuccess.styl
> fix: add folder link in konnector success display

- src/config/konnectors.json
Wait for https://github.com/cozy/cozy-konnector-uber/pull/1 before merging
> [feat] add Uber konnector

- src/components/AccountLoginForm.jsx
- src/components/Field.jsx
Compared to #217, this way don't use the `<form>` which seems to add other issues.
> Navigation using keyboard on connector modal

- src/lib/realtime.js
More robust realtime:
* Now reconnects on unexpected websocket closing
* Add a keep alive (ping) feature to avoid idle sockets
* Close connection when window closes
> feat: better realtime :sparkles:

- docs/connection-state.md
> Add documentation about konnector connection state :memo:

- src/lib/CollectStore.js
New try to fix empty folderId on old konnector. I am not able to understand where the error comes from.
> fix: trying to fix empty folder ID for legacy konnectors :ambulance:

- src/ducks/connections/account.js
- src/ducks/connections/index.js
- src/ducks/connections/konnector.js
- src/ducks/connections/test/connections.spec.js
- src/lib/CollectStore.js
- src/reducers/index.js
Thanks to @goldoraf and @ticabri for their many tips. After a few tries I think that I have now something that looks like a duck.
> feat: add naive version of ducks for connections :duck::sparkles:

- manifest.webapp
- src/components/KonnectorEdit.jsx
- yarn.lock
* Revert permission change about job (waiting for change done on stack side)
* Remove error icon on sync tab when login error
* Use default account tab when login error
* Update yarn.lock
> Default tab

- src/components/KonnectorItem.jsx
fixing : https://github.com/cozy/cozy-collect/issues/277
> WIP feat: add image formats

- src/components/KonnectorItem.jsx
- src/ducks/connections/account.js
- src/ducks/connections/components/queue/queue.jsx
- src/ducks/connections/components/queue/styles.styl
- src/ducks/connections/index.js
- src/ducks/connections/konnector.js
- src/ducks/connections/test/__snapshots__/connections.spec.js.snap
- src/ducks/connections/test/connections.spec.js
- src/lib/CollectStore.js
- src/lib/icons.js
d4d04ed3dfb1a94d2862497b3fb374041e457271
Code cleaning, better abstract statuses for Queue component, more tests and better test coverage.
Error status for a connection was not reset on connection status update.
> feat: enqueue connection on success + various refactoring and fixes :sparkles:

- src/components/AccountLoginForm.jsx
- src/components/Field.jsx
- src/components/KonnectorEdit.jsx
- src/containers/AccountConnection.jsx
- src/lib/accounts.js
- test/lib/accounts.spec.js
As usual, some little fix/refactoring before impementing the main concern of this PR here: 00c707b9e27b3aeeef53c00c2aaa347eef346c7c
> feat: allow connections to edit configuration :sparkles:

- docs/connector-configuration.md
- src/components/AccountLoginForm.jsx
- src/containers/AccountConnection.jsx
Some little fixes after deploying to staging:
* Disable the update button when no change has been made
* Set the button busy when submitting
> feat: OAuth account editing improvement :pencil:

- src/components/AccountConnectionData.jsx
- src/components/DataItem.jsx
- src/config/konnectors.json
- test/components/__snapshots__/DataItem.spec.js.snap
> refactor: remove useless accounts and colors from konnectors config :fire:

- docs/connector-configuration.md
> docs: update konnectors doc, fix #217 :books:

- src/assets/sprites/icon-bankAccounts.svg
- src/assets/sprites/icon-bankTransactions.svg
I added datatypes for bankAccounts and bankTransactions but it turns out we need also to have icons. I propose to use the bill icon for now.
> ✨ feat: add temporary icons for bank accounts and bank transactions

- src/lib/CollectStore.js
- src/lib/jobs.js
See https://github.com/cozy/cozy-stack/blob/master/docs/jobs.md#get-jobsqueueworker-type
> feat: use new route /jobs/queue/:worker ✏️

- src/lib/CollectStore.js
- src/lib/konnectors.js
Change text of error to be more understandable IMHO
> 📚 doc: better logs

- src/components/KonnectorItem.jsx
- src/config/konnectors.json
- src/containers/AccountConnection.jsx
- src/ducks/connections/konnector.js
- src/lib/icons.js
- src/locales/en.json
* Collect can take icon from the konnector config (.icon)
* Update banking connectors to fix duplicate slugs
> Bank connectors

- src/config/collect.json
- src/config/konnectors.json
- src/index.jsx
- src/lib/CollectStore.js
- src/lib/daytime.js
- src/lib/konnectors.js
- test/lib/__snapshots__/daytime.spec.js.snap
- test/lib/__snapshots__/konnectors.spec.js.snap
- test/lib/daytime.spec.js
- test/lib/konnectors.spec.js
The goal here is to randomize the time at which a trigger is ran.
The default interval, set in Collect config, is 00:00/05:00.
Orange konnectors are customized to be ran between 15:00 and 21:00.
> feat: randomize trigger day time + allow specific ✨

- package.json
- src/lib/tutorial.js
- yarn.lock
~~⚠️ Waiting for the next release of the bar (currently v4.3.5) ⚠️~~
> Fix issue with cozy-bar DOM nodes targeting in tutorial

- src/components/ConnectedList.jsx
- src/lib/tutorial.js
- src/styles/introjs-cozy.styl
> Better intro wizard with focus on empty view image

- docs/connector-configuration.md
- src/components/KonnectorEdit.jsx
- src/components/KonnectorInstall.jsx
- src/config/konnectors.json
- src/locales/en.json
- src/styles/konnectorEdit.styl
- src/styles/konnectorInstall.styl
> Add editor detail on konnector modal (install and edit)

- src/containers/IntentService.jsx
- src/index.jsx
- src/lib/CollectStore.js
- Possibility to filter konnectors by category in the intent CREATE io.cozy.accounts
> Add account by category

- src/components/Field.jsx
- src/locales/en.json
- src/styles/field.styl
"optionnal" is written "optional" ;)
> 🐝 fix: optionnal -> optional

- src/components/KonnectorEdit.jsx
- src/components/KonnectorFolder.jsx
- src/components/KonnectorInstall.jsx
- src/containers/AccountConnection.jsx
- src/styles/konnectorFolder.styl
- src/styles/konnectorInstall.styl
Déplacement du Spinner dans le composant pour avoir un Spinner uniquememt sur la zone "folder" pour l'édition, et sur le form pour l'installation
> Improve folder fetching

- src/components/KonnectorInstall.jsx
- src/styles/konnectorInstall.styl
Last cosmetic adjusts after review.
> fix: last cosmetic adjusts

- src/components/ConnectedList.jsx
- src/components/KonnectorSuccess.jsx
- src/components/KonnectorTile.jsx
- src/components/Tile.jsx
- src/components/TriggerTile.jsx
- src/ducks/triggers/index.js
- src/reducers/index.js
- src/styles/lists.styl
> Add accounts count on providers tiles

- src/components/KonnectorTile.jsx
- src/locales/en.json
- src/styles/lists.styl
> Better accounts count UI on konnector tile

- src/config/konnectors.json
- src/ducks/triggers/index.js
- src/ducks/triggers/test/__snapshots__/triggers.spec.js.snap
- src/ducks/triggers/test/triggers.spec.js
- src/lib/CollectStore.js
@ptbrowne Thanks to confirm that there is 20 bank konnectors. :)
> feat: 'daily' frequency for Bank konnectors ✨

- src/config/konnectors.json
- src/locales/en.json
Cette PR permet d'expliciter le fait que l'on passe par notre partenaire Linxo.
Voici le résultat :
> feat: Add descriptions for linxo konnector ☺️

- src/components/KonnectorInstall.jsx
- src/containers/AccountConnection.jsx
- src/locales/en.json
- src/styles/app.styl
> Add connected accounts access link if available in KonnectorInstall

- src/components/CategoryList.jsx
- src/components/ConnectedList.jsx
- src/components/ScrollToTopOnMount.jsx
- src/containers/App.jsx
This component allows to scroll to the top of the content view each time we switch between views.
> Add and use ScrollToTopOnMount component

- src/config/konnectors.json
- src/locales/en.json
Translation in french done in transifex
> feat: add description about secret answer for hsbc connector

- src/components/KonnectorInstall.jsx
- src/components/KonnectorSuccess.jsx
- src/containers/AccountConnection.jsx
Remove title, connected link and security text on success timeout.
> Disable KonnectorInstall component parts on success timeout

- .gitignore
- app.config.js
- docs/services.md
- manifest.webapp
- package.json
- src/lib/services/cozyFetch.js
- src/lib/services/exceptions.js
- src/targets/services/triggerBouncing.js
- yarn.lock
> Add trigger bouncing service

- scripts/publish_registry.sh
Waiting for the next release of CCA to handle locales in manifest
> Update to use the new registry URL when publishing

- src/config/konnectors.json
https://trello.com/c/8TQ5LMgm/626-2-organisation-konnectors-changer-les-chemins-des-repos-dans-collect-et-mettre-en-place-les-diff%C3%A9rentes-branches-prod-recette-et
> chore: Update konnectors sources

- manifest.webapp
Intents are not working anymore, this PR fixes this.
> fix: set correct intents route in manifest 🚑

- src/config/konnectors.json
> Change payfit login field name

- src/config/maintenance.json
Reverts cozy/cozy-collect#567, captchas return 😞
> Revert "Remove SFR from konnector maintenance"

- manifest.webapp
- package.json
I made two small changes in the package.json so that
we can use [deploy2cozy](https://gitlab.cozycloud.cc/labs/maintenance#deploy2cozy) with collect.
> Small changes for collect to work with deploy2cozy

- src/components/AccountPicker.jsx
- src/components/AccountPickerItem.jsx
- src/components/KonnectorTile.jsx
- src/containers/AccountConnection.jsx
- src/containers/ConnectionManagement.jsx
- src/styles/accountConnection.styl
- src/styles/accountPicker.styl
This PR: 
* Fixes the missing konnector name in tile (oops)
* Improve UI in Account Picker
* Adds back button in modal
* The modal header has been updated in `master` and will be rebased.
> feat: account picker improvements 📝

- src/ducks/connections/index.js
I swear I've already made those change, 100% sure. But it seems they're we not actually on `master`. My bad, my reaaaaaaally bad.
> feat: delete account before trigger 💪

- src/components/ConnectedList.jsx
The button _add account_ has been forgotten in #630
> feat: add link to store in connected view 📝

- src/lib/statefulForm.jsx
This PR tries to fix a behaviour seen on staging, we suspect it is caused by konnectors with no fields or unexpected fields.
> feat: try to fix 'length of undefined' detected in production 📝

- src/components/AccountPickerItem.jsx
- src/lib/helpers.js
This PR fixes an account name error for OAuth konnectors.
> fix: prevent account name error for OAuth konnectors 🚑

- src/config/categories.json
- src/config/konnectors.json
- src/locales/en.json
"Public Service" translated to "Service publique" in transifex in french
> Add public service category

- src/locales/en.json
Transifex french translation done
> Public Services

- src/config/konnectors.json
> feat: remove theoldreader connector from testing

- src/components/AccountPicker.jsx
- src/components/AccountPickerItem.jsx
- src/styles/accountPicker.styl
> Improve account button to display status

- src/config/konnectors.json
darty, impots, cesu, pajemploi, boulanger
> feat: Enable recent connectors in production, darty, impots, cesu, pajemploi, boulanger

- src/components/AccountPickerItem.jsx
- src/styles/accountPicker.styl
> Better accounts picker label and error size handling :lipstick:

- src/config/maintenance.json
Blablacar detect the connector and put a captcha.
No dirty solution for now.
> Put Blablacar in maintenance mode for captcha

- src/components/KonnectorFolder.jsx
- src/containers/AccountConnection.jsx
- src/lib/CollectStore.js
Folder path was not handler for OAuth konnectors. This PR tries to fix it.
> bug: Handle folder path for OAuth konnectors

- src/components/AccountLoginForm.jsx
- src/components/Field.jsx
- src/components/KonnectorEdit.jsx
- src/styles/field.styl
Hope nobody will read my email address, I am too lazy to update my screen capture.
> Disables login field when editing

- src/components/AccountPicker.jsx
- src/containers/ConnectionManagement.jsx
- src/styles/connectionManagement.styl
> Display modals in fullscreen on mobile

- src/styles/lists.styl
> Display two tiles per row on mobile

- src/components/intents/CreateAccountIntent.jsx
- src/components/services/CreateAccountService.jsx
- src/styles/accountConnection.styl
- src/styles/konnectorInstall.styl
- src/styles/services.styl
> Improve account form look in intents

- src/config/konnectors.json
Please check it twice, i added it from my own fork but everything seems ok to me.
> Add konnector monoprix in testing for testing purporse only

- src/config/konnectors.json
Add it in testing for firsts tests in integration
> Add new Ldlc connector in testing mode

- src/config/konnectors.json
TO SQUASH since it's a commit cherry-picked from #754
> TO SQUASH Change source prod

- src/config/konnectors.json
> Add maifecheancier and change sources

- src/components/KonnectorEdit.jsx
- src/components/KonnectorSync.jsx
Makes debugging easier since Collect does not report this information
in its UI.
> ✨ feat: log the schedule execution of the konnector

- src/containers/ConnectionManagement.jsx
This is an attempt to fix the disappearing field values.
Need to then rebase `feature/no-more-providers`
> Fix field values disappearing

- src/components/AccountLoginForm.jsx
Avoid fields update during konnector installation and running.
> Make fields readonly when submitting

- src/config/konnectors.json
> Fix cge ipx 800 connector configuration

- src/components/KonnectorInstall.jsx
- src/containers/ConnectionManagement.jsx
> Make the 'back' button works on connection modal

- src/config/konnectors.json
> Move bank konnectors to registry

- src/components/CategoryList.jsx
> Sort konnectors alphabetically

- src/components/ConnectedList.jsx
- src/containers/AccountConnection.jsx
- src/containers/App.jsx
- src/containers/ConnectionManagement.jsx
This PR fixes the "disappearing field" issue.
It was mainly caused by a mistake in the way the Route was rendered, with a component attribute instead of a render one.
Also there was a few minor bugs.
> Fix disappearing field values

- src/components/AccountPicker.jsx
- src/containers/ConnectionManagement.jsx
- src/styles/accountConnection.styl
- src/styles/app.styl
- src/styles/connectionManagement.styl
Back button position was wrong in account picker.
> Fix back button style on account picker

- src/containers/ConnectionManagement.jsx
Everything is connected.
A regression in success button has been introduced in previous developments.
> Fix regression account creation success button

- src/components/KonnectorEdit.jsx
- src/containers/AccountConnection.jsx
Advanced settings were not working in edition modal, probably due to previous too much cleaning in prop list.
> Fix advanced settings in edition modal

- src/components/Failure.jsx
- src/components/InstalledKonnectors.jsx
- src/lib/tutorial.js
- test/components/__snapshots__/Failure.spec.js.snap
> Fix tutorial with empty view

- src/styles/services.styl
Previous fix introduced regression, adding space between modal and scrollbar.
> Fix interapp padding

- .travis.yml
- package.json
- scripts/deploy-on-cozy
- scripts/publish.js
- scripts/release-pr-template.txt
- scripts/release.sh
- yarn.lock
This PR makes collect match the workflow already in place into cozy-banks:
* `yarn release` to create a new release branch
* Call to `publish` script and `deploy-on-cozy` into travis configuration
Those new script should be integrated directly into cozy-scripts in a near future.
> Update deployment and publication scripts and workflow

- src/components/KonnectorTile.jsx
- src/locales/en.json
- src/styles/lists.styl
> Add no account label for tiles

- docs/konnector-manifest.md
The code shows it is possible : https://github.com/cozy/cozy-collect/blob/91bf081d9a4e6184ed2419d0c1e93e85adb6896b/src/components/AccountLoginForm.jsx#L23
> doc: add checkbox as possible input type

- src/components/Field.jsx
- src/components/ScrollToTopOnMount.jsx
- The focus was broking the banking account connecting
- the new layout from cozy-ui is breaking the scrollTo feature, we add more tests until fixing that in cozy-ui
> 🚑 Hot fixes

- .travis.yml
Title says it all.
I made a PR to ensure build is still safe.
> Defines MATTERMOST_CHANNEL in Travis.yml

- src/components/AccountLoginForm.jsx
- src/components/DescriptionContent.jsx
- src/components/KonnectorEdit.jsx
- src/components/KonnectorHeaderIcon.jsx
- src/components/KonnectorInstall.jsx
- src/components/intents/CreateAccountIntent.jsx
- src/containers/AccountConnection.jsx
- src/containers/ConnectionManagement.jsx
- src/locales/en.json
- src/styles/accountConnection.styl
- src/styles/descriptionContent.styl
- src/styles/field.styl
- src/styles/konnectorEdit.styl
- src/styles/konnectorHeaderIcon.styl
- src/styles/konnectorInstall.styl
- src/styles/lists.styl
- src/styles/services.styl
> Make first konnector configuration simpler

- src/styles/lists.styl
<details>
<summary>How to check CI</summary>
In Travis <a href="https://travis-ci.org/cozy/cozy-collect/builds/">logs</a>, you should see
```
Attempting to publish collect (version 0.7.6-beta.0) from https://downcloud.cozycloud.cc/upload/cozy-collect/0.7.6-8f932d80f510e1942fa09865ce3526c166b00b0e/cozy-collect.tar.gz (sha256 dd42d7b55ff3992893cc2432f23a813ded6b6766a880bdf24184d35060150fe7) to https://apps-registry.cozycloud.cc (space: collect)
Application published!
```
To check that the registry has the right version:
```curl "https://apps-registry.cozycloud.cc/collect/registry/collect" | jq '.'```
</details>
<details>
<summary>How to update a Cozy on the beta version of the registry</summary>
```
cozy-stack apps update collect registry://collect/beta --domain drazik2.mycozy.cloud
``` …
> Release 2.1.0

- src/containers/ConnectionManagement.jsx
Close correctly the success modale on "Close" button.
> Fix success closing issue

- src/config/maintenance.json
> Add enedis, macif and easyjet and remove darty.

- src/components/AccountLoginForm.jsx
- src/styles/field.styl
> Better fields styles in login form

- manifest.webapp
Release 2.2.0
<details>
<summary>How to check CI</summary>
In Travis <a href="https://travis-ci.org/cozy/cozy-collect/builds/">logs</a>, you should see
```
Attempting to publish collect (version 0.7.6-beta.0) from https://downcloud.cozycloud.cc/upload/cozy-collect/0.7.6-8f932d80f510e1942fa09865ce3526c166b00b0e/cozy-collect.tar.gz (sha256 dd42d7b55ff3992893cc2432f23a813ded6b6766a880bdf24184d35060150fe7) to https://apps-registry.cozycloud.cc (space: collect)
Application published!
```
To check that the registry has the right version:
```curl "https://apps-registry.cozycloud.cc/collect/registry/collect" | jq '.'```
</details>
<details>
<summary>How to update a Cozy on the beta version of the registry</summary>
```
cozy-stack apps update collect registry://collect/beta --domain …
```
> Release 2.2.0

- src/components/KonnectorEdit.jsx
- src/components/KonnectorInstall.jsx
- src/components/KonnectorMaintenance.jsx
- src/locales/en.json
> Better maintenance subtitle wording

- src/ducks/triggers/index.js
- src/ducks/triggers/test/__snapshots__/triggers.spec.js.snap
- src/ducks/triggers/test/triggers.spec.js
- src/lib/CollectStore.js
Here is the related stack [documentation](https://github.com/cozy/cozy-stack/blob/master/docs/jobs.md#cron-syntax) to check again
> Add monthly frequency

- src/locales/en.json
This field is needed by rtm connector : https://github.com/konnectors/rtm
Transifex is updated for french
> locale: cardNumber field addition

- docs/konnector-manifest.md
> Update manifest with new locales for fields

- src/components/KonnectorFolder.jsx
- src/locales/en.json
As the related folder feature does not work well, we remove it for now.
> Remove related folder panel

- src/components/KonnectorFolder.jsx
- src/containers/AccountConnection.jsx
- src/lib/statefulForm.jsx
Following #949, remove folder form as well.
> Remove folder form

- manifest.webapp
We don't name prefix anymore for the Home
> fix: Remove name_prefix

- docs/configuration.md
- src/config/collect.json
I've just figured out that it was outdated for a long time now.
> Update configuration documentation

- src/styles/lists.styl
- Reducing tiles container padding on mobile
- Increasing scale effect on hover for konnector tiles
(designer's request)
> fix: 🎨 UI Enhancements for Home

- src/styles/lists.styl
> fix: 🎨 Increase konnector tile hover effect

- src/styles/lists.styl
- src/targets/browser/index.jsx
- bigger konnector icons on mobile
- Konnector icon ratio fixed
- Add app title in cozy-bar on mobile
> fix: 🐛 Home UI fixes

- src/locales/en.json
- src/styles/lists.styl
- test/components/__snapshots__/Loading.test.js.snap
> feat: update locales + add notification circle

- package.json
Remove postpublish scripts from publishing
> Remove postpublish scripts

- src/components/KonnectorTile.jsx
- src/containers/AccountConnection.jsx
- src/styles/lists.styl
> Display error when no accounts

- package.json
- yarn.lock
* We now use cozy-app-publish to package/publish, no need `tar` anymore
* Use `cozy-scripts publish` instead of `cozy-app-publish` CLI
> Remove unused packages

- package.json
- src/lib/tutorial.js
- src/targets/browser/index.jsx
- yarn.lock
Use the dedicated published `intro.js-fix-cozy` package
> Use intro.js with position fix

- src/containers/ConnectionManagement.jsx
Now it doesn't break if no account/konnector found
> Don't break when konnector not found

- package.json
- src/components/KonnectorTile.jsx
- src/containers/App.jsx
- yarn.lock
Features are for now loaded from context.
So this PR make the App fetch the context and pass it to its
children as a React context.
The feature check is pretty much naive for now but will be
embeded into a dedicated library in the future.
> Hide konnector errors if flag is present in features

- .eslintrc.json
- src/components/AccountLoginForm.jsx
- src/components/Home.jsx
- src/components/KonnectorFolder.jsx
- src/containers/AccountConnection.jsx
- src/containers/ConnectionManagement.jsx
- src/lib/statefulForm.jsx
UNSAFE_* methods don't work with Preact
> Get back willReceiveProps working with Preact

- package.json
- src/components/AppTile.jsx
- src/components/KonnectorHeaderIcon.jsx
- src/components/KonnectorTile.jsx
- src/ducks/connections/components/queue/queue.jsx
- src/lib/icons.js
- yarn.lock
* Cozy-ui v17
* Use correct props for the `<AppIcon />` component
> Upgrade Cozy-ui and fix App icons

- src/targets/intents/index.jsx
Following https://github.com/cozy/cozy-home/pull/1041, Cozy-Client was missing
in intents to handle account mutations.
Intents and regular App are now using both CozyClient.
> Add CozyClient in intents

- src/containers/AccountConnection.jsx
Account creation was performed also for Oauth konnector, causing a popup blocking by browser because of the async mechanism.
> Fix Oauth popup

- src/components/KonnectorTile.jsx
- src/containers/AccountConnection.jsx
- src/locales/en.json
- src/styles/accountConnection.styl
- src/styles/lists.styl
Clicking on the message will redirect to a Store view to update the service
> Handle when an update is available

- src/components/AccountPicker.jsx
- src/components/AccountPickerItem.jsx
- src/lib/konnectors.js
- src/locales/en.json
- src/styles/accountPicker.styl
> Add update status on account item in picker

- package.json
- yarn.lock
> Revert "fix(deps): update dependency preact to v8.4.2"

- src/components/AccountPickerItem.jsx
- src/locales/en.json
- test/components/AccountPickerItem.test.js
- test/components/__snapshots__/AccountPickerItem.test.js.snap
Display update message in picker even if success + add tests
> Display update message in picker even if success

- src/components/AccountPickerItem.jsx
- src/components/KonnectorTile.jsx
- src/ducks/konnectors/index.js
- test/components/AccountPickerItem.test.js
- test/components/__snapshots__/AccountPickerItem.test.js.snap
Maintenance of konnector wasn't visible on the landing of home and on the account list
> feat(maintenance): Maintenance visible on home and account list

- docs/konnector-manifest.md
Provided information was wrong.
> Fix manifest fields label information

- src/components/AccountPickerItem.jsx
- src/components/KonnectorTile.jsx
- test/components/AccountPickerItem.spec.js
- test/components/KonnectorTile.spec.js
- test/components/__snapshots__/AccountPickerItem.spec.js.snap
- test/components/__snapshots__/KonnectorTile.spec.js.snap
> Change konnector status priorization

- package.json
- src/components/AccountLoginForm.jsx
- src/components/KonnectorEdit.jsx
- src/components/KonnectorInstall.jsx
- src/components/LegacyKonnectorInstall.jsx
- src/containers/AccountConnection.jsx
- src/containers/ConnectionManagement.jsx
- src/ducks/connections/index.js
- src/lib/CollectStore.js
- yarn.lock
Waiting for https://github.com/cozy/cozy-libs/pull/275 to be merged.
> Use cozy-harvest-lib to create accounts and triggers

- src/locales/en.json
> Update wording for USER_ACTION_NEEDED.OAUTH_OUTDATED error

- src/components/KonnectorEdit.jsx
> Remove title above account edition form

- src/config/maintenance.json
Please remove this maintenance status in next home release.
> chore: Remove maifecheancier from maintenance list

- src/styles/konnectorInstall.styl
> Improve small screen layout

- manifest.webapp
- package.json
- src/containers/ConnectionManagement.jsx
> Keep konnector logo and back button after success

- src/components/KonnectorSuccess.jsx
- src/styles/konnectorSuccess.styl
> Fix banks link in message success

- package.json
- src/components/KonnectorSuccess.jsx
- src/locales/en.json
- yarn.lock
The link to Banks in the success modal brings to native app if available (using AppLinker).
Depends on https://github.com/cozy/cozy-ui/pull/903. This is why the build is [red](https://travis-ci.org/cozy/cozy-home/builds/521455619#L1055).
> Native app success modals

- test/components/AccountPickerItem.spec.js
- test/components/DataItem.spec.js
- test/components/DescriptionContent.spec.js
- test/components/Failure.spec.js
- test/components/KonnectorTile.spec.js
- test/components/LegacyAccountLoginForm.spec.js
- test/components/Loading.test.js
- test/components/ReactMarkdownWrapper.test.js
- test/jestLib/setup.js
Instead of configuring Jest adapter in each test file, do it once
in jest setup file.
> refactor: Jest setup to configure enzyme adapter

- src/components/Banners/ErrorMessage.jsx
- src/components/KonnectorSync.jsx
Allow to disable/make busy the button when the trigger is running
> Pass correctly submitting prop to triggerLaunchers

- src/components/AccountLogout.jsx
- src/components/KonnectorEdit.jsx
- src/containers/AccountConnection.jsx
- src/ducks/connections/index.js
- src/ducks/connections/test/__snapshots__/connections.spec.js.snap
- src/ducks/connections/test/connections.spec.js
- src/lib/CollectStore.js
- src/reducers/index.js
Use the dedicated component from Harvest and remove the account removal related code.
Waiting for https://github.com/cozy/cozy-libs/pull/451 to be merged
> Use harvest to handle account removal

- src/components/AppTile.jsx
Links in the home will open the native app if it installed.
> feat: Wrap AppTile into AppLinker

- package.json
- src/targets/browser/index.jsx
- test/components/Banners/__snapshots__/ErrorMessage.spec.js.snap
- yarn.lock
~~🚫 https://github.com/cozy/cozy-libs/pull/462~~
This PR replace the `handleOAuthResponse` handler by its counterpart from cozy-harvest-lib
> OAuth: Use Harvest response handler

- src/ducks/connections/index.js
This commit has been removed from the git history for a weird reason :s
> Fix delete trigger

- package.json
- scripts/check-locales.sh
Compares en.json and fr.json keys
Duplicate of https://github.com/cozy/cozy-home/pull/1076 with a branch on `origin`.
> Check fr locales (from branch on origin) ✨

- package.json
- yarn.lock
Upgrade cozy-harvest-lib to fix oauth callback in konnector
> fix: Upgrade harvest to fix oauth konnector

- jest.config.js
- package.json
- src/ducks/connections/components/queue/styles.styl
- src/styles/error.styl
- yarn.lock
Waiting on #1310, only the last commit matters.
Upgrades further than ui 22.3.0 break, I haven't found out why yet.
> Upgrade cozy-ui

- package.json
- yarn.lock
Upgrade harvest to fix icon issue
> feat: Upgrade harvest

- package.json
- yarn.lock
We had an issue when an OAuth account didn't have a accountLogin
> fix(cozy-harvest-lib): Fix KonnectorModal OAuth account issue

- jest.config.js
- manifest.webapp
- package.json
- src/components/BanksLink.jsx
- src/components/DescriptionContent.jsx
- src/components/KonnectorHeaderIcon.jsx
- src/components/KonnectorInstall.jsx
- src/components/KonnectorMaintenance.jsx
- src/components/KonnectorSuccess.jsx
- src/components/LoadingPlaceholder.jsx
- src/components/TriggerFolderLink.jsx
- src/containers/AccountConnection.jsx
- src/ducks/connections/components/queue/queue.jsx
- src/targets/services/updateAccounts.js
- test/components/Banners/ErrorMessage.spec.js
- yarn.lock
Starts the script that updates `io.cozy.accounts` after they have changed in the vault.
- Adds a new service and trigger
- Sets some global variables for the node env that aren't available in all versions
- Inits the clients
- Starts the main script from harvest
This PR needs https://github.com/cozy/cozy-libs/pull/801
> Service to update accounts

- src/ducks/connections/components/queue/styles.styl
- src/styles/accountLoginForm.styl
- src/styles/app.styl
- src/styles/dialog.styl
- src/styles/intents.styl
- src/styles/introjs-cozy.styl
- src/styles/konnectorInstall.styl
- src/styles/konnectorMaintenance.styl
- src/styles/konnectorSuccess.styl
- src/styles/lists.styl
- src/styles/placeholder.styl
- src/styles/triggerFolderLink.styl
Since the latest upgrade of UI we need to use the CSS variables.
This PR brings back the light :)
> fix: Bring me back the ligh'

- package.json
- yarn.lock
OAuth accounts don't propose to edit the credentials anymore
> fix(deps): Update cozy-harvest-lib to v1.10.1

- package.json
- src/components/Failure.jsx
- src/containers/App.jsx
- src/styles/lists.styl
- test/components/__snapshots__/Failure.spec.js.snap
- yarn.lock
Fixes a few problems detailed un the commit messages, and adds visual separators between the services.
> Icon separators

- package.json
- yarn.lock
> feat: Update harvest

- .github/auto-merge.yml
Activate auto merge
Only after 1 positive review and all positive checks, a branch with
"merge" label will be auto merged.
> chore: Auto merge

- src/components/AddServiceTile.jsx
- src/components/NoServicesList.jsx
- src/styles/lists.styl
- test/components/__snapshots__/NoServicesList.spec.jsx.snap
- Prevents app name descenders to be cut off
- Reduce margin between title and text on empty konnector screen
> Micro UI fixes

- package.json
- src/components/AppTile.jsx
- yarn.lock
Use cozy-client to properly format app names.
> feat: Translate app names

- package.json
- src/components/KonnectorErrors.jsx
- src/components/KonnectorErrors.spec.jsx
- src/components/__snapshots__/EmptyServicesListTip.spec.jsx.snap
- src/components/__snapshots__/Services.spec.jsx.snap
- src/styles/app.styl
- src/styles/lists.styl
- test/AppLike.jsx
- test/components/Banners/__snapshots__/ErrorMessage.spec.js.snap
- test/components/Banners/__snapshots__/UpdateMessage.spec.js.snap
- test/components/__snapshots__/Failure.spec.js.snap
- yarn.lock
Slightly reworked the KonnectorErrors component to be more compact.
Before:
After:
> Adjust errors

- src/components/KonnectorErrors.jsx
- src/components/KonnectorErrors.spec.jsx
Do not show slide indicator when there is only 1 slide.
> feat: Do not show slide indicator when only 1 slide

- package.json
- src/ducks/connections/index.js
- yarn.lock
- Update cozy-realtime to support "notified" message
- Have selector return null instead of false fixes a PropType warning
> Update cozy-realtime + proptype warning

- jest.config.js
- manifest.webapp
- package.json
- src/components/KonnectorErrors.spec.jsx
- src/components/KonnectorInstall.jsx
- src/containers/AccountConnection.jsx
- src/containers/App.spec.jsx
- src/targets/services/updateAccounts.js
- test/components/KonnectorInstall.spec.jsx
- test/components/KonnectorTile.spec.jsx
- yarn.lock
This branch received all other PRs while working on password manager features. So everything has been reviewed already. This is still small, so if you can take a look at it, it's cool :)
> Password manager features

- package.json
- yarn.lock
Includes https://github.com/cozy/cozy-libs/pull/928
> fix: Upgarde harvest

- package.json
- yarn.lock
Custom konnector policy functionality. The change is behind a flag so it should not be a problem.
> Upgrade cozy-harvest-lib

- package.json
- src/containers/App.jsx
Add minilog and plug it to window so that libs can share the minilog instance
with the app
> feat: Add minilog and plug it to window

- manifest.webapp
- package.json
- src/targets/services/deleteAccounts.js
- src/targets/services/polyfillFetch.js
- src/targets/services/polyfillFetch.spec.js
- src/targets/services/updateAccounts.js
- yarn.lock
This service is executed everytime a cipher is deleted. See
https://github.com/cozy/cozy-libs/pull/942.
It searches the accounts linked to the deleted cipher and delete them.
> feat: Add deleteAccounts service

- package.json
- yarn.lock
Correct mapping for SCA_REQUIRED.
> feat: Update cozy-harvest-lib

- package.json
- src/components/HeroHeader/HelpButton.jsx
- src/components/HeroHeader/LogoutButton.jsx
- src/components/HeroHeader/index.jsx
- src/components/HeroHeader/index.spec.jsx
- src/locales/en.json
- yarn.lock
Similar to the logout and settings button, this PR adds a help button in the top corner. it is visible by default but can be toggled off with a feature flag.
> Help link in the top corner

- manifest.webapp
- package.json
> chore: Bump version

- src/locales/en.json
Rebasing a commit from the latest beta.
> fix: Changed help link

- package.json
- src/components/Applications.jsx
- src/components/Applications.spec.jsx
- src/components/LogoutTile.jsx
- src/components/ShortcutTile.jsx
- src/components/ShortcutTile.spec.jsx
- src/hooks/useHomeShortcuts.js
- src/locales/en.json
- yarn.lock
In this PR we check the content of a special folder in the Cozy for any `.url` files, and display those on the main bar of the home. URL files have a default icon, but if we find a custom icon in the files metadata, we use that instead.
> Home links

- src/components/ShortcutTile.jsx
- src/components/ShortcutTile.spec.jsx
Small change, we want to open URL files in separate tabs.
> feat: Open shortcuts in new window

- package.json
- yarn.lock
Especially to get https://github.com/cozy/cozy-libs/pull/1006
> chore(deps): Upgrade cozy-harvest-lib

- package.json
- yarn.lock
> fix: Update non cozy shared cipher correctly saves it

- package.json
- yarn.lock
And especially for SCA_REQUIRED error
> feat: upgrade harvest to get last 2FA locales

- src/appContext.js
- src/appContext.spec.js
- src/targets/browser/index.jsx
- src/targets/intents/index.jsx
Bad initialisation of the legacy cozy client would crash the
intents.
> Fix intents

- package.json
- yarn.lock
See https://github.com/cozy/cozy-libs/pull/1066#pullrequestreview-476798906
> feat: upgrade harvest to get website link

- package.json
- yarn.lock
See https://github.com/cozy/cozy-libs/pull/1069
> fix: upgrade harvest to get website link with last styles

- manifest.webapp
- package.json
- src/targets/services/softDeleteOrRestoreAccounts.js
- yarn.lock
This declares the trigger for the softDeleleteOrRestoreAccount service, which itself calls the service from cozy-harvest-lib, introduced in  cozy/cozy-libs#1104
> feat: Add softDeleleteOrRestoreAccount service 

- src/components/Services.jsx
- src/components/Services.spec.jsx
Problem: when clicking on the logout button, the page becomes blank
Why: While awaiting for the client to completely logout, the components can receive
collections with data = null.
Solution: Defensive code checking for null.
> fix: Defensive code for component to work while logging out

- package.json
- yarn.lock
Upgrade harvest to benefit from https://github.com/cozy/cozy-libs/pull/1193
> feat: Upgrade cozy-harvest-lib for account rescue

- src/targets/services/attributesHelpers.js
- src/targets/services/attributesHelpers.spec.js
- src/targets/services/myselfFromIdenties.js
- Move code in attributesHelpers.js to test more simply
- Add tests about updateMyselfWithIdentity function
> fix: Move split part code in attributesHelpers

- manifest.webapp
- package.json
> chore: Bump version to 1.35.0 

- jest.config.js
- manifest.webapp
- package.json
- src/components/Konnector.jsx
- yarn.lock
- Configure harvest to show all available data cards (only geo data card available at the moment)
- Add geo data cards dependencies (leaflet)
> feat: Show geo data card in Harvest

- package.json
- yarn.lock
To have the onFocus on the Field component
> feat: Update Cozy-UI to 48.0.0

- package.json
- src/components/Applications.jsx
- src/components/Applications.spec.jsx
- src/components/Services.jsx
- src/components/ShortcutTile.jsx
- src/hooks/useHomeShortcuts.js
- src/queries.js
- test/AppLike.jsx
- yarn.lock
Use named queries enables caching and reuse of query data.
> feat: Named queries

- package.json
- yarn.lock
Necessary  to update Bi mapping.
> feat: Upgrade Harvest for mapping

- package.json
- yarn.lock
See  https://github.com/cozy/cozy-libs/pull/1320
> fix: ESC on the Viewer doesn't close Harvest

- package.json
- src/targets/browser/index.ejs
- src/targets/intents/index.ejs
- yarn.lock
La modale de déverrouillage de la vault se base sur ces `capabilities` pour afficher les bonnes informations.
Notion introduite par le version 20 de cozy-client https://github.com/cozy/cozy-client/releases/tag/v20.0.0
Suite à https://github.com/cozy/cozy-client/pull/968 les `capabilities` sont ajoutées automatiquement à client lors de son instanciation.
> Add capabilities to CozyClient

- .gitignore
- package.json
- src/components/AppWrapper.jsx
- src/targets/mobile/index.ejs
- src/targets/mobile/index.jsx
- yarn.lock
Adds cozy-client initialization from window object, which will be fed by
the mobile application
> feat: Add mobile build

- src/components/AddServiceTile.jsx
- src/components/CandidateCategoryTile.jsx
- src/components/FallbackCandidateServiceTile.jsx
- src/components/HeroHeader/index.jsx
- src/components/HeroHeader/index.spec.jsx
> Fix getInstanceOptions returned data and default wallpaper

- manifest.webapp
- package.json
> chore: Bump to 1.41.0

- package.json
- yarn.lock
by getting https://github.com/cozy/cozy-libs/commit/4f5db85
> fix: Label Height for Harvest

- manifest.webapp
- package.json
_(If not, please remove this last section.)_
> Bump version from 1.41.0 to 1.42.0

- src/ducks/connections/index.js
- src/ducks/triggers/index.js
- src/lib/HomeStore.js
- src/reducers/index.js
- feat: Handle triggers of type client in addition to konnector
Also filters triggers with client and konnector type of worker but this needs https://github.com/cozy/cozy-client/pull/962 to work
> feat: Handle triggers of type client in addition to konnector

- CHANGELOG.md
- package.json
- yarn.lock
To get the new version of cozy-bi-auth and the new BI slug for palatine bank
> feat: Upgrade Harvest to 6.6.0

- CHANGELOG.md
- config/webpack.config.cozy-home.js
> feat: Change piwik.cozycloud.cc to matomo.cozycloud.cc

- package.json
- yarn.lock
For this minor change : https://github.com/cozy/cozy-libs/pull/1366
> feat: Upgrade cozy-harvest-lib package

- package.json
- yarn.lock
See https://github.com/cozy/cozy-libs/pull/1375
> feat: Upgrade harvest to get the geojson app redirection

- config/webpack.config.cozy-home.js
- package.json
- src/targets/browser/index.ejs
- yarn.lock
Since cozy-bar is not used anymore in the Home,
let's remove it!
> refactor: Remove cozy-bar

- src/styles/app.styl
- src/styles/lists.styl
- fix: Help and Quit buttons not clickable on firefox
- fix: Wrong grid layout on mobile
> fix: Visual tweaks after visual review

- package.json
- yarn.lock
> feat: Upgrade cozy-harvest to get geojson link button improvements

- package.json
- yarn.lock
See https://github.com/cozy/cozy-libs/pull/1386
> feat: Upgradde harvest to get fix on GeoCard

- package.json
- src/components/Applications.jsx
- src/components/CandidateCategoryTile.jsx
- src/components/CandidateServiceTile.jsx
- src/components/FallbackCandidateServiceTile.jsx
- src/components/KonnectorErrors.jsx
- src/components/KonnectorTile.jsx
- src/components/LogoutTile.jsx
- src/components/Shortcuts/ShortcutsView.jsx
- src/styles/lists.styl
- yarn.lock
- feat: Upgrade cozy-ui
- feat: Use SquareAppIcon in more components
- fix: Pass type=konnector option to SquareAppIcon
- style: Clean ununsed css
> fix: Various action before release

- src/components/HeroHeader/LogoutButton.jsx
A declarative "Intent-like" service must be used instead of inlined conditionals with wild strings
> feat: Implement rough AA logout

- CHANGELOG.md
- manifest.webapp
- package.json
- chore: Update changelog
- chore: Bump version in master
> chore : Update changelog + bump version

- CHANGELOG.md
- manifest.webapp
- package.json
> feat: Upgrade to 1.45.0

- src/components/HeroHeader/LogoutButton.jsx
Since we will use a remote home in Amiral, we need the postMessage here
> feat: Add webview logout

- CHANGELOG.md
- package.json
- yarn.lock
To get the correct contact mail in error messages, according to the
context configuration
https://github.com/cozy/cozy-libs/pull/1392
> feat: Upgrade Harvest -> mail contact

- package.json
- yarn.lock
Necessary for AppLinker
Breaking change is handled
> feat: Update cozy-ui

- .travis.yml
- package.json
We should still run our tests on node 12.
> chore: Run tests on Node 12

- package.json
- yarn.lock
> feat: Upgrade cozy-intent

- .travis.yml
Forgot to run the script before deploying
> chore: Add build to stage build

- package.json
- yarn.lock
This will fix a page refresh caused by AppLinker
> feat: Bump cozy-ui to latest

- CHANGELOG.md
- package.json
- yarn.lock
We get that by upgrading cozy-harvest-lib to 7.3.0
> feat: Do not allow multiple accounts with same BI connection ID

- package.json
- yarn.lock
This will fix a thrown error in amiral home
> fix: Upgrade cozy-intent to latest

- package.json
- yarn.lock
Upgrade of cozy-script to 6.1.5 or else yarn start does not work :
Can't resolve 'cozy-bar/dist/cozy-bar.min.js'
> fix: Yarn start

- package.json
- yarn.lock
> fix(home): react-hot-loader needed when yarn start local

- package.json
- src/components/AppTile.jsx
- yarn.lock
It is needed to handle openApp animation
> feat: Pass iconRef to SquareAppIcon

- src/components/MainView.jsx
- src/containers/App.jsx
- src/styles/app.styl
Might be my environment but there seems to be some FPS drops?
> feat: Hide home UI top/bottom Amiral App

- package.json
> chore(scripts): Script yarn start is yarn watch

- CHANGELOG.md
- package.json
- yarn.lock
> fix(deps): Upgrade cozy-flags to remove useless some warnings flag.enable

- package.json
- yarn.lock
This will fix the broken navigation on connectors
when trying to go back.
> fix: Update cozy-harvest-lib

- CHANGELOG.md
- package.json
- yarn.lock
To get a correct mapping of bnp_es and cic_es https://github.com/cozy/cozy-libs/commit/f304f8978f1857f3f1d1e74c0c19385ab96dde24
To fix https://trello.com/c/DOoMt0WV/381-les-connecteurs-bnpp-incoh%C3%A9rents
> fix: Ugrade harvest to 8.2.1

- package.json
- yarn.lock
Used for file viewer navigation
> fix: Update cozy-harvest

- src/ducks/connections/index.js
- src/ducks/jobs/index.js
- src/ducks/jobs/test/jobs.spec.js
Since the upgrade to date-fns v2
https://github.com/cozy/cozy-home/pull/1318 we had a new warning in
the console : "date-fns doesn't export default"
So the code was not working anymore. But in fact this was a dead code,
so let's remove it
> refactor: Remove dead code

- .bundlemonrc
- CHANGELOG.md
- src/components/AppWrapper.jsx
- src/components/AppWrapper.spec.jsx
- src/lib/HomeStore.js
- src/lib/HomeStore.spec.js
- src/lib/redux-cozy-client/reducer.js
- src/lib/redux-cozy-client/reducer.spec.js
- src/queries.js
Adding realtime on Konnectors and Apps.
> feat(realtime): update apps and konnectors in realtime

- CHANGELOG.md
- package.json
- yarn.lock
Needed to get https://github.com/cozy/cozy-libs/blob/master/packages/cozy-harvest-lib/CHANGELOG.md#900-2022-04-29
> fix: Blank form from Intent

- CHANGELOG.md
- package.json
- yarn.lock
To get the possibility to create a BI connection with webview
Note: this needs the activation of the harvest.bi.webview and a specific
configuration of account types.
> feat: Upgrade cozy-harvest-lib to version 9.2.1

- .eslintrc.json
- src/lib/PiwikHashRouter.js
- src/lib/redux-cozy-client/middleware.js
Goal is to stop warnings this kind of errors, to keep console clean for debugging
> fix(lint): follow linter recommandation and make it stricter.

- CHANGELOG.md
- package.json
- yarn.lock
This fixes a bug when opening a PDF from Harvest
display was truncated
> fix(deps): Upgrade Cozy-UI to v67.0.1

- src/components/Failure.jsx
- src/styles/lists.styl
Text was black and everything was stacked,
added vertical spacing and white color
Also added H padding for mobile
> fix: Improve Failure component styles

- src/components/HeroHeader/index.jsx
- src/hooks/useInstanceSettings.jsx
- src/targets/browser/index.jsx
* Use better fallback for publicname
* Fix instanceSettings hook, it didn't return good values
* Put WebviewIntentProvider at the top of the app,
it was suffering from multiple renders
> fix: Fix multiple homepage issues

- CHANGELOG.md
- package.json
- yarn.lock
To get custom intentsApi prop for TriggerManager [PR](https://github.com/cozy/cozy-libs/pull/1663)
> feat: Upgrade harvest to 9.10.1

- package.json
- yarn.lock
This will remove some flickering on connector modal opening
> fix: Upgrade cozy-harvest-lib

- package.json
- yarn.lock
Updating to latest cozy-ui to get improved AppLinker logging
> fix: Remove AppLinker console spamming

- src/components/AppWrapper.jsx
- src/components/ConditionalWrapper.spec.tsx
- src/components/ConditionalWrapper.tsx
- src/containers/App.jsx
Refactored some of the App and AppWrapper code that created
unwanted rerenders at App mount, and also spammed
the console with errors.
It is hoped this can be a step further to good first paint on App Amiral
From:
To:
> fix: Clean up app bootstrap

- src/targets/browser/index.jsx
that part was not deleted, apparently
> chore(service-worker): remove service worker registration

- src/components/Applications.jsx
Instead of checking the fetchStatus,
we just display apps as soon as we have apps.
Persistor or no persistor is handled the same, we just want apps to show
> fix: Simplify onApp ready trigger

- src/components/HeroHeader/LogoutButton.jsx
- src/components/HeroHeader/LogoutModal.tsx
- src/cozy-ui.d.ts
- src/locales/en.json
- src/locales/fr.json
This will only be used on flagship app
> feat: Add a ConfirmDialog when logging out

- package.json
- yarn.lock
To fix OAuth konnector issue in flagship app
To fix Label on OAuth button
> fix: Upgrade Harvest

- package.json
- yarn.lock
Updating cozy-ui to remove the bug
> fix: Apply top/bottom spacing on dialog fullscreen

- CHANGELOG.md
- package.json
- yarn.lock
To fix a regression when trying to create a new account for an OAuth
connector, OAuth window not opening
https://github.com/cozy/cozy-libs/commit/e8293f659d3d9bb643fb528b4328885ba451e79e
> fix: Upgrade cozy-harvest-lib to 9.26.8

- src/components/CandidateCategoryTile.jsx
- src/components/Services.jsx
- src/components/Services.spec.jsx
- src/config/candidates.json
```
* Hide fallback category konnectors in maintenance
```
> feat: Hide fallbacks connector in maintenance

- src/components/AppWrapper.jsx
- src/containers/App.jsx
AddButton was in AppWrapper and therefore displayed in Intent. I moved it in App so it is not displayed in Intent (so it is not displayed in the iframe when we install a konnector from the store).
```
*  Hide AddButton on Intent
```
> fix: Hide AddButton on Intent

- package.json
- src/containers/App.spec.jsx
- yarn.lock
Will be used for updated BottomSheet
> feat: upgrade cozy-ui to latest (79.3.0)

- .tx/config
- CONTRIBUTING.md
```
* Migrate transifex config from v2 to v3
```
> chore: Migrate transifex config from v2 to v3

- package.json
- yarn.lock
```
* OAuth and client-side Konnectors have a new interface when the user did not link an account yet
```
> feat: new connector card

- package.json
- yarn.lock
- This will fix harvest connection overlay
> feat: update cozy-harvest-lib to latest

- package.json
- yarn.lock
This will fix an issue with squareAppIcons spacing
> feat: update cozy-ui to latest

- src/components/HeroHeader/index.jsx
```
* User's avatar is hidden for screen readers
```
> fix: Hide avatar to screen readers

- package.json
- yarn.lock
This will improve CCC behaviour in Harvest (make configtab account not clickable)
> feat: update cozy-harvest-lib to 13.10

- src/components/AddButton/helpers.js
```
* Update disable office edition flag
```
> feat: Update disable office edition flag

- src/components/AddButton/helpers.js
```
* Update default actions OnlyOffice on touchScreen
```
> feat: Update default actions OnlyOffice on touchScreen

- src/styles/app.styl
It is not needed anymore as Harvest has been updated to the new API.
> fix: remove harvest dialog hack

- package.json
- yarn.lock
This will allow better navigation
> feat: upgrade harvest to latest

- src/components/ShortcutLink.jsx
```
* Also show shortcut icon when in png
```
> feat: Show shortcut icon in png

- package.json
- yarn.lock
Will display new header style for config page
> feat: upgrade cozy-harvest-lib to 13.14

- package.json
- yarn.lock
This will add end animations to icon loading.
> feat: update cozy-ui to 83

- package.json
- yarn.lock
```
* Update wording for konnectors errors
```
> feat: Upgrade cozy-harvest-lib to get new locales

- manifest.webapp
- package.json
Since there is a release branch for 1.51.0
> chore: Bump version to 1.52.0

- package.json
- yarn.lock
```
* fix error on account disconnect
```
> fix: Upgrade cozy-harvest-lib to an account disconnect error

- package.json
- yarn.lock
This will fix small modals having their close button pushed down
> fix: update cozy-ui@84.1.5 for modal buttons

- src/components/AppWrapper.jsx
- src/lib/HomeStore.js
- src/lib/HomeStore.spec.js
see https://github.com/cozy/cozy-libs/pull/2212 to have a better understanding of the issue.
> fix: Always use the singleton instance of cozy-realtime

- package.json
- src/components/AppWrapper.jsx
- src/lib/konnectors_typed.ts
- yarn.lock
Needed https://github.com/cozy/cozy-client/commit/d589bae138c3092021179c7066e045e26357ef09
> fix: Set the fresh data as data to show

- package.json
- yarn.lock
```
* Connexion from the Store intent was broken for banking and oauth connexion. 
```
> fix: Banking & OAuth connexion fromt the intent

- manifest.webapp
- package.json
```
* Bump version to 1.59.0
```
> feat: Bump version to 1.59.0

- src/components/FooterLogo/FooterLogo.jsx
- src/components/Home.jsx
- src/targets/browser/index.jsx
This new flag is useful with the arrival of white-label applications
```
* Replace the page title with the home.override-title flag
```
> feat: Replace the page title with the home.override-title flag

- manifest.webapp
- package.json
```
* Bump version to 1.63.0
```
> feat: Bump version to 1.63.0

- src/components/MainView.jsx
```
* Adapt Footer placement to match Flagship application constraint
```
> fix: Adapt Footer placement to match Flagship application constraint

- src/components/MainView.jsx
```
* Adapt Footer placement to match Flagship application constraint
```
> Merge back of correction done during beta of 1.62.0

- src/components/Home.jsx
- src/components/KonnectorErrors.jsx
- src/components/__snapshots__/KonnectorErrors.spec.jsx.snap
- src/locales/en.json
- src/locales/fr.json
```
* Swap the shortcut and service sections to make shortcuts easier to read
```
> feat: Improve shortcut readability

- src/components/AppHighlightAlert/BackupAppHighlightAlert.jsx
- src/components/Applications.jsx
```
* Use correctly component key to increase stability and performance
```
> fix: Move key up to avoid warning

- manifest.webapp
- package.json
```
* Bump version to 1.64.0
```
> feat: Bump version to 1.64.0

- .bundlemonrc
- package.json
- src/components/Services.jsx
- yarn.lock
```
* Update cozy-harvest-lib from 18.2.1 to 20.1.0
```
> feat: Update cozy-harvest-lib from 18.2.1 to 20.1.0

- package.json
- yarn.lock
```
* Update cozy-client from 42.0.0 to 42.0.1
```
> feat: Update cozy-client from 42.0.0 to 42.0.1

- package.json
- yarn.lock
* This will fix statusBar color issues in cozy-flagship
> fix: update harvest from 20.1.0 to 20.1.1

- package.json
- yarn.lock
```
* Update cozy-harvest-lib from 20.1.1 to 20.1.2
```
> feat: Update cozy-harvest-lib from 20.1.1 to 20.1.2

- manifest.webapp
- package.json
```
* Bump version to 1.66.0
```
> feat: Bump version to 1.66.0

- package.json
- yarn.lock
```
* Update cozy-harvest-lib from 20.1.2 to 20.1.5
```
> feat: Update cozy-harvest-lib from 20.1.2 to 20.1.5

- package.json
- yarn.lock
```
* Update cozy-harvest-lib from 20.1.5 to 20.1.6
```
> feat: Update cozy-harvest-lib from 20.1.5 to 20.1.6

- manifest.webapp
- package.json
```
* Bump version to 1.67.0
```
> feat: Bump version to 1.67.0

- manifest.webapp
- package.json
```
* Bump version to 1.68.0
```
> feat: Bump version to 1.68.0

- package.json
- src/components/AppHighlightAlert/AppHighlightAlert.jsx
- src/components/BackupNotification/BackupNotification.jsx
- src/styles/backupNotification.styl
- yarn.lock
```
* Backup notification and app highlight alert are now correctly displayed on a light theme
```
**Normal theme (same as before)**
**Light theme**
> Display correctly backup notification and app highlight alert on a light theme

- .bundlemonrc
- package.json
- yarn.lock
```
* Update cozy-client from 42.0.1 to 45.0.1
* Update cozy-harvest-lib from 20.2.5 to 21.0.0
```
> feat: Update cozy-harvest-lib from 20.2.5 to 21.0.0

- .travis.yml
> chore: Disable travis npm cache

- .bundlemonrc
- src/targets/intents/index.jsx
```
* Fix style issue on the intent page.
```
> [VO-218] fix: Import cozy ui's styles

- package.json
- yarn.lock
To get fixes for konnectors 2FA and login update
```
* Harvest: Do not disable submit buton when password is the same
* Harvest: No more disabled submit button on 2nd 2FA
```
> fix: Upgrade cozy-harvest-lib to 22.0.8

- package.json
- yarn.lock
```
* Upgrade cozy-ui to 103.12.0
```
> feat: Upgrade cozy-ui to 103.12.0

- package.json
- yarn.lock
```
* Update cozy-harvest from 22.5.1 into 22.5.2
```
> feat: Update cozy-harvest from 22.5.1 into 22.5.2

- package.json
- yarn.lock
```
* Update cozy-harvest-lib from 22.5.2 to 22.5.5
```
> feat: Update cozy-harvest-lib from 22.5.2 to 22.5.5

- package.json
- yarn.lock
```
* Update cozy-harvest-lib from 22.5.5 to 22.5.6
```
> feat: Update cozy-harvest-lib from 22.5.5 to 22.5.6

- package.json
- yarn.lock
```
* Update cozy-harvest-lib from 22.5.6 to 22.5.7
```
> feat: Update cozy-harvest-lib to 22.5.7

- package.json
- src/components/AppWrapper.jsx
- yarn.lock
```
* Update cozy-harvest-lib from 22.5.7 to 22.5.8
```
> feat: Update cozy-harvest-lib from 22.5.7 to 22.5.8

- src/components/BackgroundContainer.tsx
- src/hooks/useCustomWallpaper.jsx
- src/hooks/useCustomWallpaperContext.tsx
- src/hooks/usePreferedTheme.ts
- src/styles/app.styl
```
* Reworks logic for background classes
```
> Reworks logic for background classes

- src/components/KonnectorTile.jsx
- src/components/Sections/SectionAppGroup.tsx
- src/components/Sections/SectionView.tsx
* Better handling of konnector suggestion click (no new tab)
> Merge back 1.77.1 to 1.78.0

- src/components/Sections/SectionView.tsx
Don't show add more services in shortcuts categories
> fix: only show addservice in service category

- src/components/FooterLogo/FooterLogo.jsx
```
* Adjust footer logo colors according to the theme
```
> feat: Adjust footer logo colors according to the theme

- package.json
- yarn.lock
```
* Update cozy-keys-lib from 6.1.0 to 6.1.1
```
> [VO-889] feat: Update cozy-keys-lib from 6.1.0 to 6.1.1

- package.json
- yarn.lock
```
* Update cozy-ui from 110.3.1 to 110.8.1
```
> [VO-889] feat: Update cozy-ui from 110.3.1 to 110.8.1

- package.json
- yarn.lock
This update get a fix the crash of the viewer inside harvest modal
```
* Update cozy-ui from 110.8.1 to 110.8.2
```
> [VO-903] feat: Update cozy-ui from 110.8.1 to 110.8.2

- package.json
- yarn.lock
This a merge back from 1.78.1 which is contain this PR : https://github.com/cozy/cozy-home/pull/2155
> feat: Merge back 1.78.1

- src/components/BackgroundContainer.tsx
- src/global.d.ts
- src/styles/backgroundContainer.styl
for animations to work on mobile
```
* Move default background from css to img tag
```
> feat: Move default background from css to img tag

- src/components/BackgroundContainer.tsx
- src/styles/app.styl
- src/styles/backgroundContainer.styl
```
* Move customWallpaper after empty div for overrides
* Background wasn't fullscreen in browser with small screen
* Scrollbar was over the content
```
> Micro adjust css for background in some cases

- .bundlemonrc
- jest.config.js
- package.json
- src/components/FooterLogo/FooterLogo.spec.jsx
- src/containers/App.jsx
- src/lib/sentry.js
- test/jestLib/json-transformer.js
- yarn.lock
> [VO-330] feat: Add Sentry

- package.json
- yarn.lock
```
* Update cozy-harvest-lib from 27.0.1 to 29.0.0
```
> [VO-330] feat: Update cozy-harvest-lib from 27.0.1 to 29.0.0

- package.json
- src/components/Announcements/Announcements.tsx
- src/components/Announcements/AnnouncementsDialogContent.tsx
- src/components/Announcements/helpers.spec.js
- src/components/Announcements/types.ts
- src/hooks/useAnnouncements.tsx
- yarn.lock
```
* Update cozy-ui from 111.8.1 to 111.9.0
```
> [VO-710] fix(announcements): Small improvements and fixes

- src/components/HeroHeader/Corner.spec.jsx
- src/components/HeroHeader/HelpButton.tsx
```
* Change help link according to context data
```
> feat: Change help link according to context data

- src/components/Announcements/AnnouncementsDialog.tsx
- src/components/Announcements/AnnouncementsDialogContent.tsx
- src/cozy-ui.d.ts
This PR is already approved to be merge on master : https://github.com/cozy/cozy-home/pull/2195
> fix(Announcements): Third round of feedback [merge for 1.81.0-beta.3] 

- src/components/BackgroundContainer.tsx
this is not the final solution, it's a temporary quick fix
> fix: Default background wasn't full width on safari

- src/assistant/ResultMenu/ResultMenu.jsx
should probably be dealt in cozy-ui, i'm working on it
> feat(Assistant): Adjust search result height in flagshipApp

- src/components/Home.jsx
```
* Devtools was imported twice
```
> fix: Devtools was imported twice

- src/locales/en.json
- src/locales/fr.json
This is a new iteration of #2233
> fix: Change wording for announcements "don't show again" button

- src/assistant/AssistantProvider.jsx
- src/assistant/Conversations/ChatConversation.jsx
- src/assistant/Conversations/Conversation.jsx
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/it.json
- src/locales/ja.json
- src/locales/nl_NL.json
it's necessary to use a dependency on the useRealtime hook to avoid subscribing/unsubscribing at each render and therefore losing information
> fix(Assistant): Rework realtime usage for instant messages

- docs/develop.md
- package.json
- src/containers/App.jsx
- src/targets/browser/index.ejs
- src/targets/browser/renderApp.tsx
- yarn.lock
index.ejs body style was added for testing purpose previously but it was
conflicting with cozy-bar that's why I removed it
> feat: Add cozy-bar when in Twake theme

- package.json
- yarn.lock
See
https://github.com/cozy/cozy-libs/compare/cozy-search%400.8.1...cozy-search%400.8.3
> fix: Get latest fixes on AI assistant

- package.json
- src/components/Applications.jsx
- src/components/Applications.spec.jsx
- src/components/Sections/SectionAppGroup.tsx
- src/components/Sections/hooks/useMagicFolder.ts
- src/components/ShortcutLink.jsx
- src/containers/App.jsx
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/it.json
- src/locales/ja.json
- src/locales/nl_NL.json
- src/locales/ru.json
- src/locales/vi.json
- src/queries.js
- yarn.lock
To update: 
- https://github.com/cozy/cozy-bar/pull/884
- https://github.com/cozy/cozy-client/pull/1637
> Add shortcut in top bar

- src/components/Applications.jsx
- src/components/Applications.spec.jsx
- src/components/ApplicationsAndServices.jsx
- src/components/EntrypointLink.jsx
See https://github.com/cozy/cozy-drive/pull/3525 for more explanation.
**Results**
> feat: New doc, new spreadsheet and new slide shortcuts
