- app/components/AccountConnection.jsx
- app/containers/ConnectorManagement.jsx
- app/lib/MyAccountsStore.js
- app/lib/accounts.js
- app/lib/konnectors.js
- app/locales/en.json
- package.json
- vendor/assets/manifest.webapp
- yarn.lock
This PR follows https://github.com/cozy/cozy-my-accounts/pull/1 and implements [konnector workflow described here](https://github.com/cozy/cozy-stack/blob/master/docs/konnectors_workflow_example.md) until step 6.
So, there is still to do :
I used two new library : `accounts` and `konnectors`. They are built like cozy-client-js ones and I think we should keep this format for all our library accessing our business objects.
> feat: rewrite add account for stack v3

- app/components/Loading.jsx
- app/containers/IntentService.jsx
- app/initKonnectors.json
- app/lib/MyAccountsStore.js
- app/locales/en.json
- app/services.ejs
- app/services.jsx
- app/styles/index.styl
- app/styles/loading.styl
- app/styles/services.styl
- config/webpack.config.prod.js
- config/webpack.vars.js
- vendor/assets/manifest.webapp
- webpack.config.js
WIP because of a wepback issue, see below. All the reste can be commented or discussed.
This PR declares a new route to serve services for intents (For now, only `CREATE` on `io.cozy.accounts` used in onboarding. See https://github.com/cozy/cozy-onboarding-v3/pull/26.
I tried several solutions to find the optimal way to serve this new route.
1. Specifying a fragment in the intent route, for example `#/services`. It should have been useful to use ReactRouter to directly redirect to the intent service component. But it does not works well, react router does not detect correctly the query string and it implies more code.
2. Define the app root as intent href, for example `/`, as proposed by @nono. But again, React Router adds a `#/` fragment to the URL and we still have to get the intent id …
> feat: serve mocked intent for CREATE io.cozy.accounts

- package.json
- yarn.lock
Fix also errors in console about proptypes with ReactMarkdown when opening modals.
> Update preact and react-markdown dependencies

- src/components/AccountConnection.jsx
- src/containers/ConnectorManagement.jsx
- src/containers/IntentService.jsx
- src/initKonnectors.json
- src/lib/DataConnectStore.js
- src/lib/accounts.js
- src/lib/konnectors.js
- src/lib/statefulForm.jsx
- src/locales/en.json
Ok, the first commit add the `folderId` information to an account, this is the last step of the whole account connection process. Maybe it should have been into a separate PR.
At that time, and at least in my development environment, the process fails at permission creation, as the feature is not yet implemented in the stack. At least my local one.
> refactor: account creation and konnector run :art:

- src/components/AccountManagement.jsx
- src/containers/ConnectorManagement.jsx
- src/styles/dialog.styl
This removes the account list and account creation button in the connector management dialog. I also removed unused styles.
This commit will be tagged so that we can add multiple accounts back when needed.
> clean: MC-27 Removed multiple accounts

- src/lib/accounts.js
In my connector, `email` is used.
fixes https://github.com/cozy/cozy-data-connect/issues/54
> fix(accounts): allow fields other than login/password

- src/initKonnectors.json
Bouygues Telecom konnector used phoneNumber field as login field and it does not match with the cozy-collect application at the moment
> fix: set login field for bouygues telecom konnector

- src/locales/en.json
Default folder name for Connectors switches from `Administration` to `Administrative` (in English) and `Administratif` (in French, see transifex).
> feat: Change default folder name

- src/containers/App.jsx
`window(.location).origin` seems to not be completely supported by all/older browsers, here is a fix.
> Fix issue for undefined window.origin case :bug:

- src/initKonnectors.json
- src/locales/en.json
Orange vod connector was displaying bill datatype
> fix: change orange vod datatype to videostream + locale

- src/lib/CollectStore.js
There was a "r.konnector.attributes is undefined" error when running a konnector which was already
installed.
This fetches the konnector slug in a path which exists in any case (according to my tests)
> fix: remove bad error message when running a konnector for the second time

- src/containers/AccountConnection.jsx
These parameters added to the /...start/ url help for the maif OAuth but it does not affect orange OAuth
> fix: added some parameter for maif oauth

- src/lib/CollectStore.js
When updating connector list, installed konnectors were setting an empty category.
> fix: sanitize konnector at update to avoid empty categories :ambulance:

- src/components/AccountLoginForm.jsx
- src/components/Field.jsx
- src/containers/AccountConnection.jsx
Use unique names on input should avoid the browser autofill to fill wrong connector forms.
> Add unique names to form inputs to wrong autofills :bug:

- src/containers/AccountConnection.jsx
Only login/password were saved in the account
Continuation of https://github.com/cozy/cozy-collect/pull/56
> feat: allow other fields than login/password in auth

- src/components/ConnectorList.jsx
- src/containers/AccountConnection.jsx
- src/containers/ConnectorManagement.jsx
- src/lib/CollectStore.js
CC-2
This displays the error message in the modal if the given connector was errored in the last run
with the previously entered fields, ready to change.
> feat: display previous error in modification modal

- src/components/AccountLoginForm.jsx
The edf connector uses an "email" fields as identifier. We need another attribute in the manifest
to define the identifier field
> fix: show disconnect button event when no login field in the connector

- src/lib/CollectStore.js
This will allow the worker queue to be lighter.
Also, try to make all the trigger not run the same day
> feat: now run the trigger every week

- package.json
- src/containers/IntentService.jsx
- yarn.lock
This changes the size of the intent modal for intents related to an oauth connector which does not have much content to display.
Do not merge yet since this needs a release of cozy-client-js which is not done yet.
> feat: set max size for oauth connector intent

- src/config/konnectors.json
- src/lib/konnectors.js
This is the hotfix for prod changing the url of the edf connector to gitlab with obfuscation
> fix: 'security' fix :-D

- src/lib/statefulComponent.jsx
When the user sets the password field to visible and gets back to the list of connectors, he/she
want's it to go back to not visible when he displays that form again or the form for another
connector.
> fix: password field gets back to invisible when coming to the form

- src/config/konnectors.json
- src/lib/konnectors.js
Base64 encode is of no use anymore since we now allow private repos.
> fix: remove base64 encoding of source + edf source with ssh

- src/containers/AccountConnection.jsx
I was not understanding how this only `!success` condition was causing `KonnectorSync` display or not. It appears that it is always computed ans displayed, but luckily when the account has no sync date it shows only an empty div. This was causing unecessary props in https://github.com/cozy/cozy-collect/pull/195
> feat: better KonnectorSyncCondition :pencil:

- src/containers/AccountConnection.jsx
`KonnectorFolder` was displayed randomly when connecting a new account.
> fix: better KonnectorFolder condition :ambulance:

- src/components/KonnectorFolder.jsx
- src/containers/AccountConnection.jsx
And with this, the display of the MAIF connector form does not break the page
> fix: add folderPath handling for OAuth connectors

- src/components/KonnectorItem.jsx
- src/components/KonnectorList.jsx
- src/components/KonnectorSync.jsx
- src/containers/AccountConnection.jsx
- src/containers/App.jsx
- src/index.jsx
- src/lib/CollectStore.js
- src/lib/jobs.js
- src/lib/konnectors.js
- src/lib/realtime.js
- src/locales/en.json
- src/styles/konnectorItem.styl
In this PR `CollectStore` starts to behave like a redux state, and now contains a few `Map` of synced objects.
You need to have a redis instance running locally
```
docker run -p 6379:6379 redis
```
And store jobs in redis, so add this configuration to your `cozy.yaml``
```yaml
jobs:
workers: 1
url: redis://localhost:6379/5
```
Until now we were guessing connection statuses thanks to hackish condition on konnector accounts. From now, we will be only relying on konnectorResult documents.
```js
this.konnectorResults = new Map()
```
A list of running jobs is added in store, fetch at startup and maintained up to date thanks to realtime.
```js
this.runningJobs = new Map()
```
Those two previous improvements are a good example of what should be the next evolutions of `CollectStore`, and looks …
> feat: realtime for connection statuses :sparkles:

- src/lib/realtime.js
Add missing `:`.
Look for http instead of https to detect bugs locally instead of directly in staging/production.
> fix: typo in websocket protocol detection :ambulance:

- package.json
- src/lib/tutorial.js
- yarn.lock
Makes it possible to click everywhere on the overlay to advance the tutorial, regardless of the device, as requested [here](https://trello.com/c/GJUsCLjm/455-glob-%F0%9F%90%9B-toute-la-zone-nest-pas-cliquable-dans-le-wizard-de-collect).
> feat: enable click-everywhere on every device

- src/containers/AccountConnection.jsx
When real time fails for jobs for a reason or another, we need to get the error message from the KonnectorResult.
> fix: get error from Konnector Result when no reatime for jobs :ambulance:

- src/components/AccountLoginForm.jsx
- src/config/konnectors.json
- src/containers/AccountConnection.jsx
- src/lib/CollectStore.js
- src/lib/accounts.js
- test/lib/accounts.spec.js
* Handle account fields in case of oauth connector (need for a checkbox for Orange Mobile)
* Remove unused 'PENDING' status in account doc
* Cherry pick the commit from #223 to get back Orange konnectors (Thanks @jacquarg 👍 )
* Handle correctly OAuth scope directly from the konnector manifest
> Oauth connexion fixes

- src/lib/CollectStore.js
- src/lib/jobs.js
Queued jobs were not loaded at startup, so konnector statuses in collect was inapropriate.
> feat: load queued jobs as unfinished jobs at startup :ambulance:

- .babelrc
- config/webpack.config.cozy-collect.js
- config/webpack.config.dev.js
- package.json
- src/containers/App.jsx
- src/ducks/konnectors/index.js
- src/ducks/registry/index.js
- src/index.jsx
- src/lib/CollectStore.js
- src/lib/redux-cozy-client/CozyAPI.js
- src/lib/redux-cozy-client/CozyClient.js
- src/lib/redux-cozy-client/CozyProvider.jsx
- src/lib/redux-cozy-client/README.md
- src/lib/redux-cozy-client/__tests__/store.spec.js
- src/lib/redux-cozy-client/connect.jsx
- src/lib/redux-cozy-client/helpers.js
- src/lib/redux-cozy-client/index.js
- src/lib/redux-cozy-client/middleware.js
- src/lib/redux-cozy-client/reducer.js
- src/lib/redux-cozy-client/utils.js
- src/reducers/index.js
- src/store/configureStore.js
- yarn.lock
I tried to make the more commit as possible to log every step of adding redux and redux-cozy-client.
From now, the redux store is merged with the old one, and do not interfere with existing features.
About the registry duck:
It takes the konnector from the existing config file, but it will evolve in the future to fetch them from cozy-store/registry. For now it was a simple case to test, first for redux, second for having a custom state with a redux-cozy-client state.
> feat: add redux and redux-cozy-client :sparkles:

- manifest.webapp
Specify the jobs permissions to explicitly ask for the `konnector` worker. This evolution is required by this change in cozy-stack: https://github.com/cozy/cozy-stack/pull/950
> Specify the jobs permissions

- src/components/Field.jsx
Autocomplete seems to still appear on password we reveal it (so it become a text input).
This changes try to keep the autocomplete disabled in all cases.
Insteresting links:
[MDN autocomplete and login fields](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields)
[HTML Spec autocomplete](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-new-password)
> Fix autocomplete proposal

- src/components/AccountLoginForm.jsx
- src/components/KonnectorInstall.jsx
- src/containers/AccountConnection.jsx
When errors were occuring in Cozy-Collect or during job run, it was possible to try a new connection.
In the stack, this was resulting with the creation of a new account. It may occurred that multiple accounts were coexisting in DB, one by error.
The goal of this PR is to prevent this case to happen by disabling the connection form once one OAuth process has been terminated. The only way next for users is to try again in the edition modal or to delete their account.
> feat: prevent mulitple OAuth accounts creation ✨

- .travis.yml
- package.json
- src/lib/accounts.js
- test/lib/accounts.spec.js
- yarn.lock
Now we must use all fields of an index in a query selector.
> Fix all broken index usages with CouchDB 2.1.1

- src/components/AccountLoginForm.jsx
- src/lib/statefulForm.jsx
- test/components/AccountLoginForm.spec.js
- test/components/__snapshots__/AccountLoginForm.spec.js.snap
Error was due to https://github.com/cozy/cozy-collect/commit/21d661f#diff-4d5e78ed80ff9b0c288e11a2d8e4505aR78
I tried to set up some kind of tests for `statefulForm` but I did not succeed.
> fix: make OAuth form valid 🚑

- src/config/konnectors.json
- src/locales/en.json
The french version is :
```
"USER_ACTION_NEEDED": {
"title": "Action nécessaire chez le fournisseur",
"description": "Il semble que le site [%{name}](%{link}) ait besoin que vous vous authentifiez dessus pour faire une action spécifique. Merci de relancer le connecteur une fois cette action effectuée."
}
```
> fix: ameli vendor link + better USER_ACTION_NEEDED message

- docs/connector-configuration.md
- src/components/AccountLoginForm.jsx
- src/components/KonnectorEdit.jsx
- src/components/KonnectorFolder.jsx
- src/components/KonnectorInstall.jsx
- src/components/KonnectorSuccess.jsx
- src/config/advancedFields.js
- src/containers/AccountConnection.jsx
- src/containers/ConnectorManagement.jsx
- src/lib/CollectStore.js
- src/lib/statefulForm.jsx
- src/locales/en.json
- test/components/AccountLoginForm.spec.js
- yarn.lock
L'idée est de déplacer toute la logique formulaire dans AccountConnection / ConnectorManagement pour garder le même état partout, et alléger le statefulForm de code spécifique.
- Déplacer le `fetchFolders` dans `AccountConnetion`, pour éviter le `<select>` vide quand on affiche le champ de `folderPath`
- Passer le `statefulform` seulement dans `AccountConnection`, pour avoir le même form dans tous les composants enfants (Edit, Install, AccountLogin, etc), contre seulement dans `AccountLoginForm` précédement
- Préparer les values qu'on doit modifier avant de les injecter (`namePath` / `folderPath`) dans le composant parent du `statefulForm` (`ConnectorManagement`) pour que le statefulForm en hérite en props, et le garder le plus abstrait possible
- Suppression du champ `frequency` non …
> feat: clean statefulForm

- src/config/konnectors.json
Société Générale connectors where previously splitted into several ones (Entreprises, Professionnels, Particuliers, Associations...). These changes create a single entry "Société Générale" in which you have a dropdown to choose the branch you want to connect to.
> feat: group Société Générale connectors

- docs/connector-configuration.md
- src/components/Field.jsx
- src/components/KonnectorEdit.jsx
- src/components/KonnectorFolder.jsx
- src/config/konnectors.json
- src/containers/AccountConnection.jsx
- src/containers/ConnectorManagement.jsx
- src/lib/CollectStore.js
- Ajout du déplacement d'un dossier
- Suppression du `FolderPickerField` devenu inutile
- Suppression de la variable `foldersFromStack` qui gardaie en cache la liste des dossiers, empêchant de la fetcher à nouveau après l'installation / la modification d'un connecteur
- Fermeture de la modal de connecteur une fois le dossier modifié, au lieu de revenir sur l'onglet de modification
> feat: improve folder path modifications

- src/config/konnectors.json
It was a mistake to copy the configuration of the linxo connectors. The numbers are not the same for all agencies.
Here we use a list generated directly from the main credit agricole website
> fix: credit agricole by cozy connector : use our own agencies list

- src/components/CategoryList.jsx
- src/ducks/registry/index.js
- src/index.jsx
Konnector list was not consistent between displayed list an redux registry.
I connected `<CategoryList />` to redux.
> fix: ensure consistency between displayed konnector and redux registry 🚑

- src/components/services/CreateAccountService.jsx
values.namePath is from the "old" feature of folderPath.
> fix: remove namePaht on intent

- src/reducers/index.js
We are now gathering konnector information from "registry" (i.e. konnectors configured in the file `config/konnectors.json`), instead of gathering from database.
The goal is to avoid the display of Linxo konnector in _Connected Services_.
> fix: avoid konnector Linxo to be shown in connected services 📝

- src/lib/daytime.js
- test/lib/__snapshots__/daytime.spec.js.snap
- test/lib/daytime.spec.js
Supports [6.5, 7.5] as timeInterval, meaning between 6:30AM and 7:30AM.
Previously, minutes were all across the clocks (`randomize(0, 60)`) so if you put [6.5, 7.5], you could get 6:15AM or 7:57AM.
> ✨ feat: support float in timeInterval

- src/config/konnectors.json
⚠️ https://github.com/cozy/cozy-collect/pull/435 should be merged before
Banking connectors should be launched between 6:30AM and 7:30AM.
> ✨ feat: add timeInterval for banking connectors

- src/ducks/connections/components/queue/queue.jsx
Depuis le passage à Redux, le state de la file d'attente est dépendant du store, donc il est mis à jour plus régulièrement. 
Là où le composant était "figé" une fois monté, il reçoit maintenant des nouvelles props à chaque changement du store.
La méthode componentDidUpdate "historique" n'est donc plus correcte pour masquer la file d'attente.
> fix: componentDidUpdate was buggy on connections queue

- src/ducks/connections/index.js
- src/lib/CollectStore.js
That's a quick fix to avoid new bugs before the launch.
> feat: increase delay from 7 to 10 seconds

- src/ducks/registry/index.js
Context can now have a `debug` property. When set to `true`,  it shows Debug konnector and Banking konnectors.
> feat: filter konnectors categories based on context ✨

- src/components/KonnectorInstall.jsx
- src/locales/en.json
Banking konnector use Linxo as a third party, so we can't say "Nobody will access it!"
> fix: remove "Nobody will access it!" for banking account

- src/config/konnectors.json
Because geopoints are availables hourly.
> Set hourly frequency on orangemobile

- src/config/konnectors.json
Voici la branche coté cozy-konnector-linxo : https://gitlab.cozycloud.cc/labs/cozy-konnector-linxo/tree/latest
Le but étant d'avoir la même nomenclature que les apps:
- master -> build
- prod -> latest
> feat: Update git url to linxo konnector

- src/config/konnectors.json
Remove max constraint on Malakoff Mederic password.
The password length seems to be incorrect. It's fixed at 15 characters but it can actually be longer (mine is 128).
> Remove max constraint on Malakoff Mederic password

- src/ducks/registry/index.js
Sanitize konnectors from registry and ensure they all have a `categories` attribute.
Prevent missing or malformed `categories` attribute from manifest.
> feat: sanitize konnectors categories ✨

- src/config/konnectors.json
- src/locales/en.json
I forgot a field in #497. This fixes it. Sorry.
> fix: add missing field for Barclays konnector

- src/config/konnectors.json
- src/ducks/registry/index.js
From a proposition from @ptbrowne, this PR allow to specify directly in `src/config/konnectors.json`  if a konnector is in "testing" mode and should appear only on instances having a context with `debug` to `true` (i.e. at least not in **production**)
See https://github.com/cozy/cozy-stack/blob/master/cozy.example.yaml#L223
> feat: add testing attribute for in konnectors.json ✨

- src/targets/services/cleanOrphanAccounts.js
- src/targets/services/triggerBouncing.js
We got this error when running the `cleanOrphanAccounts` service at the `io.cozy.accounts` cleaning step:
```
Stderr: /usr/src/konnector/index.js:4234
var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee() {
^
ReferenceError: regeneratorRuntime is not defined
```
It seems to be due to the missing polyfill, so let's fix it.
> Add polyfill in services

- src/targets/services/cleanOrphanAccounts.js
The leading slash was causing "Resource not found" when testing.
> fix: no need for leading slash in cozyFetch routes

- src/ducks/connections/components/queue/styles.styl
- src/styles/KonnectorSync.styl
- src/styles/accountConnection.styl
- src/styles/accountConnectionData.styl
- src/styles/accountLoginForm.styl
- src/styles/accountLogout.styl
- src/styles/app.styl
- src/styles/connectedTile.styl
- src/styles/connectionManagement.styl
- src/styles/dataItem.styl
- src/styles/dialog.styl
- src/styles/field.styl
- src/styles/index.styl
- src/styles/konnectorEdit.styl
- src/styles/konnectorFolder.styl
- src/styles/konnectorInstall.styl
- src/styles/konnectorMaintenance.styl
- src/styles/konnectorSuccess.styl
- src/styles/lists.styl
- src/styles/loading.styl
- src/styles/notifier.styl
- src/styles/services.styl
- src/styles/sidebar.styl
Remove deprecated em() and *only import what's needed*. This improve build time from 46s to 26s.
> Remove deprecated em()

- src/components/appEntryPoint.jsx
- src/containers/App.jsx
- src/containers/IntentHandler.jsx
`IntentHandler` and  `App` are sharing the same logic for initialization. This PR provide an HOC to mutualize this part.
> feat: use HOC appEntryPoint to mutualize logic between app an intents 🔨

- src/config/konnectors.json
Mise à jour des dépots des connecteurs suivant :
- bouyguesbox
- bouyguestelecom
- free
- free mobile
- numericable
- orange
- orange mobile
- sosh
Déplacement dans l'organisation https://github.com/konnectors + changement de branche #build en #latest
> feat: Update mobile & telecom konnectors source 📞

- src/config/konnectors.json
Suppression du tag testing.
Les 2 banques ne sont plus en erreur coté Linxo.
> feat: Remove testing of Bred & Crédit Coopératif

- src/lib/accounts.js
- test/lib/accounts.spec.js
Avoid to remove account data in `io.cozy.accounts` when updating the account in collect.
> fix: do not remove accont data while updating password

- src/config/konnectors.json
Add bank categorization connector in testing mode. This connector's goal is to collect the user's bank operations to send it to @francoisWeber algorithm.
> feat: add bank categorization konnector (testing)

- src/config/konnectors.json
- src/locales/en.json
This allows users to set the field `timeout` which may be used by `cozy-konnector-debug`, [see here](https://github.com/cozy/cozy-konnector-debug/blob/master/index.js#L6).
> feat: add timeout field for Debug konnector ⏳

- src/targets/services/cleanOrphanAccounts.js
We rely on internal stack events to trigger post deletion jobs. The deletion
event does not seem to be correclty sent when using the
bulk route. This is surprising as some work had been done to ensure the right
event was sent (https://github.com/cozy/cozy-stack/pull/1272).
Here I go back to the previous method of deleting one by one each document to
ensure we have something working.
> fix: do not use bulk for deletion as delete events are not sent by the stack

- src/components/ConnectedList.jsx
- src/components/KonnectorHeaderIcon.jsx
- src/components/KonnectorSuccess.jsx
- src/components/services/CreateAccountService.jsx
- src/containers/AccountConnection.jsx
- src/containers/ConnectionManagement.jsx
- src/styles/accountConnection.styl
- src/styles/accountConnectionData.styl
- src/styles/konnectorHeaderIcon.styl
- src/styles/konnectorInstall.styl
- src/styles/lists.styl
- src/styles/services.styl
> fix: cozy-ui regressions 💄

- src/config/konnectors.json
We updated the connector which now needs a wider scope, notably to retrieve the email address of the user's google account in order to be able to do the binding between cozy contacts and google contacts.
See https://github.com/konnectors/cozy-konnector-google/pull/22 for more details about the needs.
> feat: update google konnector's scope

- src/config/konnectors.json
* sncf
* payfit
* enercoop
* directenergie
* digiposte
* trainline
have moved to the konnectors organization and prod/latest branches have been
created.
> ✨ feat: change branch and org of some konnectors

- src/components/ConnectedList.jsx
- src/components/appEntryPoint.jsx
- src/ducks/apps/index.js
- src/lib/redux-cozy-client/CozyClient.js
- src/lib/redux-cozy-client/adapters/CozyStackAdapter.js
- src/lib/redux-cozy-client/index.js
- src/lib/redux-cozy-client/reducer.js
This PR links the button _Connect my accounts_ directly to the Cozy-Store app.
To do this, we :
* Load the apps list in cozy redux state, so the version of `redux-cozy-client` needs a little update. @goldoraf showed me how special collections are handled in the next version of `redux-cozy-client` but it needs more work and we are a little bit short for this card. I hope to get he next version of `redux-cozy-client` later.
* Select the store app and get its url.
> feat: link directly to the store ✨

- src/config/konnectors.json
- src/locales/en.json
Make Enedis konnector viewable (but it should be only usable by MesInfos users for now !)
Update description. The french translation would be :
Récupérez vos données Linky en connectant votre compte Enedis. Vous devez être équipé d’un compteur Linky et avoir au préalable créé votre espace client Enedis (sur le [site Enedis](https://espace-client-connexion.enedis.fr/auth/UI/Login?realm=particuliers)). Ce connecteur est fourni par la Fing pour le projet MesInfos. Il récupère les données de votre contrat d’électricité et télécharge tous les matins votre consommation d’électricité de la veille. Ce connecteur est exécuté sur votre Cozy et  la Fing n'aura aucun accès à ces données.
ping @poupotte  : )
If this PR relies on changes …
> Make enedis connector available. Update description message.

- src/components/intents/CreateAccountIntent.jsx
- src/containers/IntentService.jsx
There a side effect at the end of an intent, which is automatically terminated. To fix this behavior, we need to dive deep into Modal's logic and it will need a little time. Waiting for this, we just close the intent when the account creation is done.
> Fix intent termination

- src/config/konnectors.json
Use registry source for connectors with stable versions published
> Use registry for published connectors

- src/components/KonnectorInstall.jsx
- src/components/KonnectorSuccess.jsx
- src/components/services/CreateAccountService.jsx
- src/containers/AccountConnection.jsx
- src/containers/ConnectionManagement.jsx
This PR:
* Clean a little bit some props in AccountConnection and related stuff
* Fix the behaviour at the end of an account creation, by using a common `onDone` handler between both ConnectionManagement modal and intent CreateAccountService.
Notice:
Using
```jsx
const render = props => {
const { foo, bar } = props
...
}
```
is better for linting than
```jsx
const render = ({foo, bar}) => {
...
}
```
> Better 'onDone' management in KonnectorSuccess and AccountConnection

- src/components/AccountLoginForm.jsx
- src/components/KonnectorEdit.jsx
- src/containers/AccountConnection.jsx
When trying to update an account for a OAuth konnector, the OAuth credential window was always popping up, making the use create a new account at every try.
Also, nothing was never updated.
This PR fixes this behaviour.
> OAuth accounts can now be updated

- src/locales/en.json
Some konnectors use Oauth and lose their refresh token.
This let the user knows she needs to disconnect / reconnect.
> Add actionable error message for outdated oauth

- src/config/konnectors.json
I put this new connector directly to registry. And keep it in testing for now.
I don't know if all tagged version and publish is exactly right, please check and come back to me if needed.
https://github.com/konnectors/auchandrive/releases
> Move new auchandrive connector from collect to registry

- src/components/AccountConnectionData.jsx
- src/components/AccountLoginForm.jsx
- src/components/DescriptionContent.jsx
- src/components/KonnectorEdit.jsx
- src/components/KonnectorInstall.jsx
- src/ducks/konnectors/index.js
- src/lib/konnectors.js
- src/lib/middlewares/konnectorsI18n.js
- src/store/configureStore.js
- src/styles/descriptionContent.styl
- src/targets/browser/index.jsx
- src/targets/intents/index.jsx
- test/lib/konnectors.spec.js
This PR deals with konnector i18n information from `manifest.konnector`. To achieve that, it adds a middleware module wich add new locales translation every time a konnector is added to the state (via fetch or realtime).
Alors, it handles and ensures legacy for:
* field attribute 'description' (previously 'hasDescription')
* messages like `terms` or `service` (previously `connector` and `service`)
It allows us to get beautiful modal like this one:
Adding @goldoraf as reviewer for the redux middleware part.
> Handle konnector i18n from manifest

- src/config/konnectors.json
To make LCL Linxo valid for migration purpose, we need to add a mock in `konnectors.json`
> Add temporary lcl-linxo mock

- src/components/DataItem.jsx
- src/config/konnectors.json
When a data type was missing, Collect was stopping doing anything.
This PR handle the case where the related icon is missing.
> Handle missing data types icon without crashing

- src/lib/tutorial.js
- src/targets/browser/index.jsx
The introjs css was imported after the main styles. Fixed.
> Fix: intro.js css was overwritting

- src/components/InstalledKonnectors.jsx
- src/containers/ConnectionManagement.jsx
After fixing the disappearing fields issue, the back button in the account creation modal was not working effectively in case of a konnector with no accounts.
This PR fixes this issue.
> Fix back button in new account modal

- src/components/AccountPicker.jsx
- Knock Knock
- Who's there ?
- Another bugfix related to [disappearing fields values issue](https://github.com/cozy/cozy-collect/pull/821). This time the back button on Account Picker was simply missing, I did not spot the commit responsible of its absence.
> Add missing back button on account picker

- README.md
Fixed the link for how to set the development environment in the README.md file.
> Fixed Broken Link In README

- src/ducks/triggers/index.js
- src/ducks/triggers/test/triggers.spec.js
There is no need to force `weekly` value in tests.
Also, little refactoring to avoid code repetition.
> Better frequency test

- src/components/DataItem.jsx
Icon were not loaded due to the way babel loads SVG : it needs a full path a not a variable.
> Fix missing datatype icons

- src/ducks/triggers/index.js
- src/ducks/triggers/test/__snapshots__/triggers.spec.js.snap
- src/ducks/triggers/test/triggers.spec.js
Some konnectors, sometimes, were runned with an hourly frequency instead of a daily one. But it was not reproductible.
After investigation, it appears that randomizing an `hours` value may make it to be `0`.
In the code, a `0` value was considered as falsy and was replace by an `*`, making the cron to be hourly.
> Handle trigger cron with hours set to 0 without making it hourly

- src/styles/services.styl
Margin was `auto` and it was pretty ugly in interapp iframe.
> Fix margin in interapp iframe

- src/lib/accounts.js
- test/lib/accounts.spec.js
Second password update was throwing an error caused by undefined id. This PR cleans the update method and remove the reference to `account.id`.
My `debug` konnector is failing miserabily locally but Trainline seems to work.
> Fix password update error

- src/components/KonnectorTile.jsx
- src/locales/en.json
Replacing account count by a green check mark.
The logic and method to get accounts count is still used in the edition modal, so let's keep it.
> Get the check mark back on konnector tiles

- manifest.webapp
- src/components/IntentRedirect.jsx
- src/containers/App.jsx
Quick implementation of intent redirection for collect.
In the future it should be mutualized wiht cozy-store (see https://github.com/cozy/cozy-store/pull/262) same component and embeded into cozy-interapp lib.
> Handle intent redirections for konnector accounts

- src/components/KonnectorSuccess.jsx
Clicking on "Access my account configuration" was also submitting the save folder form.
> Avoid form submit event to bubble up

- src/components/InstalledKonnectors.jsx
- src/styles/app.styl
Prevent
```
src/styles/app.styl
21  error  duplicate property or selector, consider merging see file: src/styles/app.styl for the original selector  duplicates
```
> Avoid duplicate CSS property col-top-bar

- src/components/AccountLoginForm.jsx
Avoid throwing an error when a konnector field has an unexpected type. Otherwise the whole edition modal is not displayed and it looks like a critical crash.
> Log warning instead of throwing error on unexpected field type

- .travis.yml
This PR try to make the build works for PR from forks, as forks cannot access to Travis secured vars.
> Do no copy private key in Travis build for forks

- scripts/release.sh
This PR automates the first bump version commit when starting a new release and avoid human errors, event if the version bump is in the checklist.
> Automate the bump version commit when starting a new release

- src/components/KonnectorTile.jsx
Unknown category was displayed.
This PR fixes this and ensure that a category, including _Other_ category, is not mentioned twice in the Tile.
So
will display:
> Avoid unknown category in KonnectorTile

- src/assets/sprites/icon-forbidden.svg
- src/components/KonnectorTile.jsx
- src/ducks/connections/index.js
Neutral status is shown when a konnector have an errored trigger but no user error.
> Add neutral status in konnector tile

- src/locales/en.json
Requiring some new fields for Ovh connector.
(Will reuse 'consumerKey' too)
> feat(locales): Add appKey and appSecret fields

- src/components/Applications.jsx
- src/styles/lists.styl
A intermediate div `[data-tutorial=home-apps]` has been added in the last stages of Cozy-Home integration.
The role of this div was to wrap only the App icons, making the tutorial fit perfectly the number of icons.
The side effect is that it broke the horizontal scroll on mobile.
This PR fix this horizontal scroll and keeps the tutorial required behaviour.
> Fix horizontal scroll for apps

- src/components/AccountLoginForm.jsx
This PR handle locale for field label in manifest. The manifest should look like this:
```json
{
"fields": {
"myfield": {
"label": "great.locale"
}
},
"locales": {
"en": {
"great": {
"locale": "My pretty field"
}
}
}
}
```
> **Reminder**
> This PR use the fact that all fetched konnectors have their manifest locales merged into the whole app locales, see https://github.com/cozy/cozy-home/blob/master/src/lib/middlewares/konnectorsI18n.js
So the locale of any field should be stored under the `locales.${LANG}.fields` attribute.
For example:
```json
"fields": {
"mySpecialField": {
"type": "email"
},
},
"locales": {
"fr": {
"fields": {
"mySpecialField": {
"label": "Mon champ spécial"
}
}
}
```
> Handle locale for field label

- src/components/AccountLoginForm.jsx
- src/config/collect.json
- src/containers/AccountConnection.jsx
- src/lib/statefulForm.jsx
In the case of a regression removing the locale `format.date`, this PR provides a default date format from config.
> Prevent undefined locale 'format.date'

- src/ducks/accounts/index.js
- src/ducks/connections/index.js
This PR:
* Improves error handling for account deletion, now every error is thrown
* Add a retry mechanism on 409 errors
* Add comment about trigger deletion performed by the stack
> Retry account deletion on 409 error

- src/targets/browser/index.ejs
- src/targets/intents/index.ejs
Necessary to use the new cozy-bar navigation and the home app detection
> Get app slug from stack

- src/components/AccountLoginForm.jsx
- src/lib/accounts.js
- test/lib/__snapshots__/accounts.spec.js.snap
- test/lib/accounts.spec.js
When updating account name, an empty password was erasing authentication data and making the konnector connection fail.
This PR fix this issue.
I have not been able to understand from where and when this bug was coming.
It was apparently older than the recent changes.
> Ignore empty password

- src/ducks/connections/index.js
- src/ducks/triggers/index.js
- src/lib/CollectStore.js
- src/lib/triggers.js
Also fix the remanent checkbox issue, after a 404 from the stack on trigger deletion, the redux store was not up to date and a checkmark was still visible on konnector tile.
> Realtime for triggers

- src/lib/accounts.js
- test/lib/__snapshots__/accounts.spec.js.snap
Fix f44c4d5, login was saved with an empty value when the account was updated.
> Avoid empty Login

- src/components/Applications.jsx
- src/lib/tutorial.js
Hidden apps are applications configured in database to not be show,
for example in a demo context.
The best solution should be to add a `hidden` attribute directly
to the app, but it should imply to update informations returned
by the stack.
So for now I used the `state` attribute, already returned by the
stack, to bring the information.
The switch to hidden app is for now manual.
> Filter hidden apps

- src/components/AddServiceTile.jsx
Spinner get the same size of other item icons so the text doesn't jump when the spinner appears.
NB: I didn't use the Spinner component because it wouldn't work properly with the class.
> fix: 🐛 Fixed Spinner size so it doesn't jump

- src/containers/IntentService.jsx
As the store now perform an intent composition to cozy-home to configure a installed konnector, we need to avoid a loop and tell the store to not compose.
> Update intent call to avoid configuration in store

- src/styles/lists.styl
Some cleaning in preparation for a future [release of Cozy-UI](https://github.com/cozy/cozy-ui/pull/641) with color variables as CSS custom properties.
> fix: Don't use color var in stylus func

- src/containers/AccountConnection.jsx
- src/lib/helpers.js
- src/lib/popup.js
- src/targets/browser/index.jsx
Now we use the OAuth state parameter as a key and store the account type related to the key in the local storage.
> Handling correctly konnector type from OAuth response

- src/ducks/connections/components/queue/__snapshots__/queue.spec.js.snap
- src/ducks/connections/components/queue/queue.jsx
- src/ducks/connections/components/queue/queue.spec.js
- src/ducks/connections/index.js
Use trigger Id as key to force rerendering of AppIcon,
to avoid the behaviour seen in the following screen capture:
> Add triggerId as key for AppIcon ✨

- src/components/services/CreateAccountService.jsx
- src/containers/ConnectionManagement.jsx
- src/lib/helpers.js
- src/lib/statefulForm.jsx
- src/locales/en.json
Get `defaultDir` from the konnector manifest to replace the old way to add define a folder need.
> Handling folders from manifest

- package.json
- src/connections/accounts.js
- src/connections/accounts.spec.js
- src/containers/AccountConnection.jsx
- src/lib/CollectStore.js
- src/lib/accounts.js
- src/targets/browser/index.jsx
- yarn.lock
This PR handles konnector declaring `agregator` field in their manifest.
An aggregator is a main service used by several konnectors (for example:
Budget Insight for Banking konnectors).
When an account is created, we check if the konnector declares an aggregator.
If so, we create a _master account_, which will be later filled by the konnector.
Then we relate every account of the given konnector to this master account.
This PR use CozyClient but still mix some old logic from redux-cozy-client
to keep the existant behaviour working. It also adds realtime for accounts
to keep the whole state synchronized.
> Aggregator account

- src/lib/CollectStore.js
According to documentation : /docs/konnector-manifest.md@c09f79a#L102
And no connector uses timeInterval anymore (neither orange or linxo)
> fix: use time_interval in connector manifest

- src/lib/CollectStore.js
For the facebook connector, the home receives a lot of thumbnail jobs from the WS, and it has some performance issues.
> fix: Perfs issues with thumbnail jobs received from the WS 🔥

- src/styles/accountConnection.styl
With cozy-harvest-lib, the form was not wide enough on interapp.
Before
After
> Better Account Form width

- src/locales/en.json
Better use the *accounts* word in title, less confusing than *connectors*.
Also better matches the french locale.
> fix: Empty service list wording

- src/components/Applications.jsx
The onboarding app was deprecated, and the step of choosing a password was integrated in the stack. The onboarding app is no longer installed (and have been removed from existing instances), so we can stop filtering it in home.
> chore: Remove the onboarding from the hidden apps

- config/webpack.config.cozy-home.js
- yarn.lock
We had in the bundle a log of JSON and JS for locales that we don't support. It takes a lot of spaces (several hundreds of kb) and it is not used as it's not possible to select one of those locales currently. So, let's remove them to make the home loads faster.
Note: the change has been made on cozy-home, but if it works nicely, it should probably moved to cozy-scripts.
> feat: Remove unsupported locales from the bundled JS

- src/styles/konnectorSuccess.styl
Icon was too big following https://github.com/cozy/cozy-home/pull/1121
Before:
After:
> Fix connecting icon

- src/targets/browser/index.ejs
- src/targets/intents/index.ejs
Get back the font in intents, as it is not provided
by the Cozy-Bar.
This commit is a partial revert of 06fb1fa98b37336091e11b2e40246c222240f4d7
> Fix font in intents

- src/styles/notifier.styl
Icon was too big following https://github.com/cozy/cozy-home/pull/1121
Vertical alignement was wrong.
Before:
After:
> Fix notification icon and layout

- src/targets/browser/index.ejs
Apparently ejs provides two comment syntaxes, which only one is valid.
Fixing 2489baed397a2367a488118eb50ec6c077c683b7
> Fix ejs comment

- package.json
- src/components/KonnectorInstall.jsx
- src/components/intents/CreateAccountIntent.jsx
- src/containers/AccountConnection.jsx
- src/containers/ConnectionManagement.jsx
- yarn.lock
This version of cozy-harvest-lib introduces error management and get rid of the Success view after account configuration. So Cozy-Home manage to show this view.
It implies that Home does not longer pass an `onDone` hook but a `onSuccess` instead.
`onSuccess` correspond to a fully done konnector job, where `onLoginSucccess`still correspond to a login success.
> Handle cozy-harvest-lib@0.33.0

- src/components/KonnectorInstall.jsx
- src/components/LegacyKonnectorInstall.jsx
- src/containers/AccountConnection.jsx
Simplifying Cozy-Home, one step at a time.
Here we follow https://github.com/cozy/cozy-home/pull/1140#discussion_r263044543
Here we are moving up KonnectorMaintenance component, which inform
user about konnector maintenance, from KonnectorInstall (very late)
to AccountConnection (earlier but could be better).
We also do not rely anymore on `maintenance.longTerm` as ALL
konnectors in maintenance are also in longTerm maintenance.
> Moving KonnectorMaintenance from KonnectorInstall to AccountConnection

- src/components/KonnectorInstall.jsx
- src/components/LegacyKonnectorInstall.jsx
- src/containers/AccountConnection.jsx
We discovered that a konnector job may have been queued after a login success.
This event is intented to show the success message from component KonnectorSuccessMessage.
But if the job was failing after the the success message has been shown, the KonnectorSuccessMesssage could have been "mixed" with the job error.
This PR fixes this behaviour by keeping the success message up even when the related queued job has failed.
> Fix "late job error" behaviour

- src/containers/AccountConnection.jsx
Following https://github.com/cozy/cozy-home/pull/1140/files and https://github.com/cozy/cozy-home/pull/1149/files, it seems that we need a last little adjustement.
For legacy konnector jobs, konnector icon was still present on regular job success (before login success).
This PR fixes this by updating the `ConnectionManagement`'s `isSuccess` state variable in case of `legacy` success.
> Make compatible recent success handlers with legacy

- package.json
- src/components/KonnectorEdit.jsx
- yarn.lock
When editing errors must not be shown on account form, except login errors. 
Waiting for https://github.com/cozy/cozy-libs/pull/317
> Pass showError prop to TriggerManager when editing

- src/lib/CollectStore.js
With Harvest we need to subcribe to accounts update, otherwise we could face 409 errors.
By subscribing to realtime we are aware when Harvest update an account.
> Prevent 409 on account update

- src/components/KonnectorEdit.jsx
- src/containers/AccountConnection.jsx
We don't need those callbacks here and it could cause side effects
> Remove success callback passed to TriggerManager when editing

- src/lib/CollectStore.js
- src/lib/triggers.js
Now that Harvest is launching the triggers, Cozy-Home must stay up-to-date. Fetching trigger after a job update allows us to have the error associated to the trigger and pass it to Harvest's TriggerManager.
Without these change an error on account creation is not displayed immediately when editing account right after.
> Fetch trigger after job update

- src/components/AccountLoginForm.jsx
- src/components/KonnectorEdit.jsx
- src/components/KonnectorInstall.jsx
- src/lib/CollectStore.js
Cozy-Home now rely on cozy-harvest-lib by default.
Only OAuth konnectors are managed the old fashion way.
> Remove cozy-harvest-lib flag

- src/ducks/connections/components/queue/queue.jsx
Path was broken following changes to absolute paths.
> Import style path for Queue component

- src/targets/intents/index.jsx
URL are embeding two informations : protocol (secure or not ?) and domain (url host).
I think a variable should always bring one information. But this point of view is not shared unfortunately.
> Fix CozyClient initialisation in Intents

- package.json
- src/containers/AccountConnection.jsx
- src/lib/helpers.js
- yarn.lock
Since the code in the cozy-home is now used only for OAuth konnectors, we can directly add random string in the folder path computing helper
> Use a random folder name for OAuth connection

- src/config/maintenance.json
This remove the maintenance status of Sosh connector.
Please report to @mathieumousse when the publication will occur, as we can synchronize the maintenance remove in registry.
Thank's
> Remove Sosh konnectors from Mainteance

- src/components/BanksLink.jsx
target=_top: Opens the linked document in the full body of the window
Since BanksLink is used in an intent (inside an iframe) we have
to tell the link to open the page in the full body of the window.
> fix: Use target top since BanksLink is used in an Intent

- src/components/KonnectorSuccess.jsx
- src/components/KonnectorSuccess.spec.jsx
A mistake from my end ended up costing many hours of my life.
The second parameter of mapDispatchToProps is *not* the store,
but the ownProps. The simple way to access CollectStore is
through this.context. The best way would be to access it with
a ContextProvider. This should be done when home does not use
pReact
> fix: Take banks url from store inside context

- src/lib/accounts.js
- src/lib/helpers.js
Quickfix:
Determines account name based on probableLoginFieldNames from lib/accounts.
`new_identifier` was not taken into account.
> Better account name

- src/config/maintenance.json
We add maintenance mode to darty because of datadome block.
> chore: Add Darty in maintenance mode

- src/containers/App.jsx
Move the main `Spinner` in the DOM so it can be vertically centered.
Not sure I didn't break something though. Please tell me if I did.
> fix: Main Spinner position on mobile

- src/lib/CollectStore.js
As Realtime is watching jobs with konnector worker, we are also triggering logic for hook jobs triggered when an account is deleted.
See https://github.com/cozy/cozy-stack/blob/master/model/account/accounts.go#L83
> Ignore hook jobs on account deletion

- src/containers/AccountConnection.jsx
Seems to be the source of the `t is undefined` issue when redirecting to the store
> Fix undefined konnector in UpdateMessage

- src/containers/App.jsx
`enableFlags` has been renamed to simply `enable` so it could break the home
> s/enableFlags/enable due to cozy-flags API change

- manifest.webapp
- src/components/IntentRedirect.jsx
Handle `account` parameter from query string on redirects.
`/#/redirect?konnector=foo&account=abcdef123456` will redirect to `/#/connected/foo/accounts/abcdef123456`
> Handle account parameter in redirects

- src/ducks/connections/index.js
Correctly clean the home global state and remove the trigger when the account is deleted.
> Correctly clean triggers after deletion

- manifest.webapp
- src/targets/services/myselfFromIdenties.js
This service will on on each io.cozy.identities creation or update and will update the "me" contact
with any new attribute not found in the "me" contact.
> feat: add myselfFromIdentities service to home app

- manifest.webapp
Two issues are fixed :
- permission selector values with boolean does not seem to be correctly accepted
- bad syntax for triggers with multiple events
This will allow the app to be installed
> fix: avoid malformed manifest message from stack

- .travis.yml
The version 1.2.1 of yarn is very old, and updating it to the current stable version (1.16.0) seems like the right thing to do to avoid subtle bugs.
> chore: Update yarn for travis build :wrench:

- package.json
- yarn.lock
This PR upgrade cozy-harvest-lib in order to support `defaultDir ` in the konnector manifest
> fix: Upgrade cozy harvest lib

- package.json
- yarn.lock
The cozy-bar now bundles its own cozy-ui, which should fix the stylesheets conflicts we had between the cozy-bar's cozy-ui and app's cozy-ui.
See https://github.com/cozy/cozy-bar/pull/608 for more infos.
> chore(deps): Update cozy-bar to v7.6.0

- manifest.webapp
- package.json
We're publishing 1.18.0 version. So we need to bump our dev version
> chore: Bump dev version

- .travis.yml
- package.json
- When writing tests, it's annoying to have the linter yell at us
- We mostly want coverage reports when the tests are run by travis, for the rare cases where we want to see them in dev we can add the flag manually
> Script updates

- src/ducks/connections/index.js
- src/ducks/connections/test/connections.spec.js
We added a new bit in the redux store to store trigger informations, but the same reducer also receives job informations that accidentally ended up in the same part of the store, causing problems.
I think it would be best to isolate this new part in a separate slice of the store, but I'm not familiar enough with the code base to make such a change at the moment. Instead I patched the issue and started adding tests to this big reducer.
> Fix connections reducer

- src/components/AccountPicker.jsx
Redirecting to `/` triggers a re-render of all components, including fetching the apps. The base route is actually `/connected` in this context.
> fix: Better redirect after closing modal

- src/reducers/index.js
When there is no trigger on the instance, clicking on a konnector was crashing because we tried to convert `undefined` to an object in `getTriggersByKonnector`.
> fix(Konnector): Don't crash if there is no trigger

- package.json
- src/targets/services/updateAccounts.js
- yarn.lock
When a user update a cipher which is not shared with the cozy organization, we get an error from cozy-harvest-lib. Here, we handle it to show a message in logs.
See https://github.com/cozy/cozy-libs/pull/810 for more context.
> feat(updateAccounts): Handle errors

- src/components/Banners/ErrorMessage.jsx
This was from a time where we did not have a registry yet.
And this error message is displayed for EDF on any error.
> fix: remove edf specific "temporary" error message

- src/components/FooterLogo.jsx
- src/components/FooterLogo.spec.jsx
- src/components/Home.jsx
- src/components/__snapshots__/FooterLogo.spec.jsx.snap
- src/containers/App.jsx
- src/styles/app.styl
Adds a footer at the bottom of the home page with some logos. The logos are defined in the cozy's context, and refer to dynamic assets.
I had to change the general layout of the app in order to have a sticky footer, but it should be the same as before when there isn't a footer.
> feat: Added an optional footer

- src/components/FooterLogo.jsx
- src/components/__snapshots__/FooterLogo.spec.jsx.snap
When we add a dynamic asset in a stack, we provide a URL, like `/logos/1.svg`. However, when using it from a webpage, the actual path to use is `/assets/logos/1.svg`.
This is a detail that the front-end should know about, not the context configuration file. With this PR the context data can reference the exact path used in the stack, and not worry about the `/assets` prefix.
> fix: Add /assets prefix for logos

- src/targets/intents/index.jsx
In b082ab60a6714f6d2fc2df1f37e3be464fe7b72b we changed the signature of `configureStore`, but didn't update the calling code in the intents.
> fix: Interapp window init

- src/components/Home.jsx
There are links in other apps that open on a konnector modal, but because of the redirect the user always ends up at the root fo the home. Removing the redirect fixes the problem.
The redirect was there to prevent loading non-existing pages, I will create a PR in harvest to prevent this more finely.
> fix: Remove blanket redirect

- src/components/Konnector.jsx
This goes with https://github.com/cozy/cozy-libs/pull/828. We were passing the root with a variable in it — it works, but we couldn't use the root to redirect to it because we would literally end up on `#/connected/:konnectorSlug`.
Now we're passing the actual slug, eg. `/connected/edf`. Works a bit better!
> fix: Pass exact root route to harvest

- package.json
- src/containers/App.jsx
- src/store/configureStore.js
- yarn.lock
Redux logger pollutes the console with everything that is happening.
It trains us to ignore what is in the console. With cozy-flags, we
can put it back if we want `flag('redux-logger', true)` in the console.
> feat: Redux logger behind a flag

- package.json
- src/components/KonnectorInstall.jsx
- src/containers/AccountConnection.jsx
- yarn.lock
Make the vault unlocker not closable by a modal cross but only by the « quit » button
> fix(intents): Make harvest vault unlocker work

- src/styles/app.styl
- src/styles/lists.styl
1. First commit fixes a problem on mobile where the app icons where no exactly aligned on their middle on the background image, due to a parsing bug in stylus I guess
2. Second commit: I accidentally vertically centered all the content, which means that on a screen with more content than what can fit on a page, some parts of the page were invisible
> UI bug fixes

- src/components/KonnectorTile.jsx
I removed the use of this flag [here](https://github.com/cozy/cozy-home/pull/1369/files#diff-c49bd336f6dba66952b99f88389304e9R61), thinking it wasn't used anymore… but it was. So here it is back again !
> fix: Reinstate hiding error through flag

- manifest.webapp
- package.json
Earlier, i bumped the version number to 1.21.0, but we haven't release v1.20.0 yet.
> chore: Unbump version

- package.json
- src/components/AddServiceTile.jsx
- src/hooks/useAppDataset.jsx
- src/targets/browser/index.ejs
- yarn.lock
The "add service" button was making an interapp request to find the URL of the store, and displayed a spinner while the request was being made. Instead it's now a normal link, without spinner, like the other tiles.
> Remove spinner from "add service" button

- src/targets/browser/index.ejs
Since we don't have a cozy-bar on the page anymore, we need to load the Lato font explicitly.
> fix: Load the cozy font

- src/components/AddServiceTile.jsx
I must have checked out an earlier version of the stack, since I received a `1` or `2` value. But now we receive `nested` or `flat`, so it's a bit easier !
> fix: Subdomain type variable

- src/components/FooterLogo.jsx
- src/components/__snapshots__/FooterLogo.spec.jsx.snap
Slightly changing the layout of the footer logos — our only use case now involves logos with very different ratios, so flexbox should do the work a bit better.
> fix: Better footer logo alignment

- src/config/candidates.json
- test/components/__snapshots__/NoServicesList.spec.jsx.snap
Some of the slugs were incorrect (ing and bouygues), and `impots.gouv.fr` has just been switched toi maintenance mode so we want to offer a replacement.
> fix: Candidate konnector slugs

- src/components/Applications.jsx
- src/containers/App.jsx
- src/containers/App.spec.jsx
Allows to hide certain apps though the context, by specifying them in the context yaml, for example
```
home_hidden_apps:
- drive
- banks
```
> Filter apps through context

- src/components/HeroHeader.jsx
- src/config/collect.json
- src/targets/browser/index.ejs
Using the [new DefaultWallpaper](https://github.com/cozy/cozy-stack/pull/2191) variable gives a wallpaper URL that has cache control on it.
> fix: Use cached version of the default wallpaper

- src/styles/app.styl
With lots of apps, the timeline was cutoff instead of taking as much space as available. Fixing the scroll behavior would risk breaking the scroll behavior when there is no timeline.
> fix: Prevent timeline cutoff

- src/containers/App.jsx
[I said](https://github.com/cozy/cozy-home/pull/1409#discussion_r352580548) we would unify the flag names, but actually it makes more sense to keep them separate for now, because [one of the "demo" flags](https://github.com/cozy/cozy-home/blob/master/src/components/Applications.jsx#L57) is not a simple true/false.
> fix: Rename timeline flag

- src/styles/lists.styl
On desktop, we had no margin under the service list, so when there were many services…
> fix: Add bottom margin to desktop service list

- src/components/Services.jsx
- src/components/Services.spec.jsx
- src/components/__snapshots__/Services.spec.jsx.snap
- src/config/candidates.json
This PR adds a list of backup konnectors to suggest, which is especially useful for the first connection on a cozy when there are no legitimate suggestions yet. It also sorts the real suggestions by alphabetical order.
> Candidates improvements

- src/hooks/useInstanceSettings.jsx
Following a bugfix in cozy-client, there is now a `data` in the response.
> fix: Display public name

- src/components/KonnectorErrors.jsx
- src/components/KonnectorErrors.spec.jsx
Follow up of #1418, when there was no error we were still displaying the carrousel (but empty).
> fix: Display nothing when there are no errors

- package.json
- src/components/KonnectorErrors.jsx
- src/components/KonnectorErrors.spec.jsx
- yarn.lock
We had 2 problems:
- https://github.com/cozy/cozy-client/pull/613
- On some instances, there are triggers with errors, but no matching konnector installed. This is not supposed to happen, but when it does, we need to handle it here by filtering out these errors
> Fix some konnector errors problems

- src/components/KonnectorErrors.jsx
- src/components/KonnectorErrors.spec.jsx
- src/config/collect.json
Until now we were displaying all konnector errors, but we'd rather show only errors that the user is abble to fix themselves. For this we use a whitelist of error codes that we want to show, all other errors aren't highlighted on the home page.
> fix: Ignore errors that the user can't fix

- package.json
- yarn.lock
No more proptypes warning in the console since I18n does not copy
PropTypes onto wrapping component anymore.
> feat: Update cozy-ui

- package.json
No need for a GITHUB_TOKEN, this is a relicate of an era when we deployed the
build folder on github n CI before release.
> fix: Use origin to deploy build on remote branch

- package.json
- yarn.lock
Brings this branch on par with the 1.26.0 release + links to the store for apps that aren't installed in harvest.
> feat: Upgrade harvest

- package.json
- src/components/Applications.jsx
- src/components/Applications.spec.jsx
- src/components/HeroHeader/LogoutButton.jsx
- src/components/LogoutTile.jsx
- yarn.lock
Adds the option to have a logout button at the end of main app bar. Not active by default, but will be used in places where we will deactivate the logout button in the top corner. We *could* even use a single flag for that, but I think it's more future proof to keep the dissociated.
> Logout tile

- src/components/KonnectorTile.jsx
- src/containers/App.jsx
The previous flag names did not follow the new naming convention. The new flag names are already deployed on the corresponding contexts.
> fix: Rename flags to respect naming convention

- src/styles/lists.styl
We added an optional logout button in the app bar — but since it's a button, it comes with a default border, and the corresponding css class did not explicitly remove borders.
> fix: Border for app items

- src/components/KonnectorErrors.jsx
- src/components/KonnectorErrors.spec.jsx
We have a blank screen on a few production cozies because they have error in triggers but no installed konnector
> fix: We can have triggers error but no installed konnectors

- package.json
- yarn.lock
See https://github.com/cozy/cozy-libs/pull/1026
> fix: gandi banking connectors with harvest upgrade

- .gitignore
- .travis.yml
- manifest.webapp
- package.json
- src/appContext.js
- src/components/HeroHeader/CornerButton.jsx
- src/components/KonnectorErrors.jsx
- src/locales/es.json
- src/locales/fr.json
- src/schema.js
- src/targets/browser/index.jsx
- src/targets/intents/index.jsx
- yarn.lock
- Harvest update (brings contract display/edition behind a the harvest.show-contracts)
- Refactored entrypoints (see next point)
- Schema update so that the home knows about bankAccounts (TODO, share schemas across apps via cozy-client ?)
- DX
- Store locales in repository
- Update cozy-scripts so that webpack-dev-server works correctly
> Update harvest to be able to edit contracts through the home

- package.json
- yarn.lock
This will allow cozy-home to work in maif_epa environnment and make test on
banking connectors easier
> feat: Update cozy-harvest to 2.2.0

- src/appContext.js
- src/appContext.spec.js
- src/targets/browser/index.jsx
- src/targets/intents/index.jsx
The LegacyClientProvider takes the new cozy-client, not the
ad-hoc one from the home.
> fix: Even the LegacyClientProvider takes the new cozy-client

- package.json
- yarn.lock
This is a preparation for next 1.30.6 version and for more explanation
see  https://github.com/cozy/cozy-libs/pull/1078
> feat: downgrade harvest to 2.2.1 to only get WebsiteLink component

- src/ducks/connections/index.js
- src/ducks/connections/test/__snapshots__/connections.spec.js.snap
- src/ducks/connections/test/connections.spec.js
Since banking account communicate directly with BI, when the
LOGIN_SUCCESS event is triggered, the trigger that is dispatched does
not contain an id (it is fake trigger, the trigger has not yet been
created). This would make the enqueueConnection action handling
crash with "Missing trigger id" problem.
Ignoring the action fixes the problem.
In a subsequent PR, I'll remove dead code since enqueueConnection
should no longer be used. Here I just bypass the problem and
minimize the risk to break other stuff.
> fix: Prevent flow crash when adding a banking account from intent

- src/styles/app.styl
The bar is injecting html,body{height:auto} which is messing with
the height set by the home CSS. We can see this bug due to a
change of order in the CSS. Normally the bar should not inject
this height:auto (see https://github.com/cozy/cozy-bar/issues/705)
but at the moment to solve the problem, !important is needed
> fix: Fix the height of html,body to 100%

- README.md
The link to setup the dev environment was broken in Readme
> fix: Readme link to setup dev environment

- package.json
- yarn.lock
to fix konnector modal CTA link. See https://github.com/cozy/cozy-libs/pull/1309
> feat: Update cozy-harvest-lib to 5.10.3

- CHANGELOG.md
- package.json
- src/components/Shortcuts/__snapshots__/ShortcutsView.spec.jsx.snap
- yarn.lock
To get correct display of SquareAppIcon name in 2 lines and with
ellipsis when needed
> feat: Upgrade cozy-ui to 57.5.2

- package.json
- yarn.lock
This version of harvest will be need to make 3 new banking connectors working. 
socramcredit, socrammacif, nalo
> feat: Upgrade cozy-harvest-lib for banking connectors

- CHANGELOG.md
- src/components/CandidateServiceTile.jsx
- src/styles/lists.styl
On browser other than firefox, the hover effect on icons gives a "blurry"
effect.
The zoom property does not have this problem but is not supported
by firefox.
We use @supports to get the best of both worlds
> fix: Avoid blur effect when hover icon

- src/styles/lists.styl
The previous zoom fix caused issues changing the origin of the
transformation
Also apply new design recommendations :
- scale to 1.06
- add transition ease to the transformation
> fix: Back to transform instead of zoom

- src/styles/lists.styl
On hover, the icons' text can be blurry depending on the configuration :
- browser (especially chrome and safari)
- screen resolution
We found that the text is less blurry with transform: scale(1.0625)
> style: Transform scale to 1.0625 for a less blurry text

- src/targets/browser/index.ejs
We found that the lato font was not rendered on icon
titles on mobile devices (android at least)
We then explicitely import this font, which fixes the problem.
> fix: Load lato font for mobile devices

- src/styles/lists.styl
Without this, the grid would have variable row height on desktop and mobile.
> style: Apply a fixed height to all rows of the grid

- CHANGELOG.md
- package.json
- yarn.lock
We had a bug in Harvest that when we opened
then closed then opened again the modal,
the konnector's translations were not taken
the right ones
for more information check the harvest
changelog
> fix: Wrong Label in Harvest Form

- CHANGELOG.md
- package.json
- yarn.lock
Upgrade cozy-harvest-lib to 6.14.2 to avoid a fatal error on account
creation for OAuth connectors
https://github.com/cozy/cozy-libs/pull/1390
> fix: Account creation for Oauth connectors

- CHANGELOG.md
- package.json
- yarn.lock
To get https://github.com/cozy/cozy-libs/commit/9dda46f. To change the
timeout to get BI token from createTemporaryToken job and avoid timeout
error on BI connectors.
> feat: Upgrade Harvest to 6.14.4

- docs/configuration.md
https://github.com/cozy/cozy-home/pull/1502 renamed `collect.json` config file to `home.json` however documentation link in `configuration.md` was not updated.
This PR fixes broken link
* [**N/A**] Faithful integration of the mockups at all screen sizes 
* [**N/A**] Tested on supported browsers, including responsive mode
* [**N/A**] Localized in english and french
* [**N/A**] All changes have test coverage
* [**N/A**] Updated README & CHANGELOG, if necessary
> docs: Fix broken link

- CHANGELOG.md
- package.json
- yarn.lock
To get multi-account deactivation for client side connectors
See https://github.com/cozy/cozy-libs/commit/1a9d157
And https://trello.com/c/HoTn7eGr/119-%F0%9F%9A%80%F0%9F%8F%A0-e87-d%C3%A9sactiver-le-multi-compte-sur-les-connecteurs-c%C3%B4t%C3%A9-clients-05-jh
The breaking change for cozy-harvest-lib is related to linting and has no impact on the home application
> feat: Upgrade cozy-harvest-lib to 7.1.0

- package.json
- src/components/AppTile.jsx
- src/components/MoveModal.spec.jsx
- yarn.lock
AppLinker can now send app data to the native host in order to open the
native app when available instead of its webview version
---
Related PRs: https://github.com/cozy/cozy-ui/pull/2015 and https://github.com/cozy/cozy-react-native/pull/65
---
TODO:
> feat: Open apps using their native mobile version when available

- CHANGELOG.md
- package.json
- src/containers/App.jsx
- src/containers/toFlagNames.js
- src/containers/toFlagNames.spec.js
- yarn.lock
- Send hideSplashScreen message to Flagship app when Home App is ready
- related to https://github.com/cozy/cozy-react-native/pull/94
- related to https://github.com/cozy/cozy-libs/pull/1478
- Refactor App component in order to use the `useWebviewIntent` hook
- Clean App code during the refactor
> feat(splashscreen): hide splashscreen when app is ready

- CHANGELOG.md
- src/styles/app.styl
Navigation bar and url bar used to always appear completely
Only bug on Safari ios device
The height 100% came from an issue from cozy-bar to fix
> style(home): don't set height 100% on mobile, it blocks ios safari address bar always displayed

- CHANGELOG.md
- src/containers/App.jsx
- src/containers/App.spec.jsx
This prevents scrolling inside cozy-native-app, that shows white background
> fix(app): BackgroundImage has fixed position

- src/serviceWorker/service-worker.js
Fix bug when installing a new version, the service worker is not activated. Skip waiting prevents that behaviour
> fix(service-worker): install new service worker without waiting

- src/styles/app.styl
> fix(styles): background filter should be fixed over the full page

- package.json
- yarn.lock
This version retrieves a fix that prevented to open connector's files
when the home was displayed on the flagship app
Related PR: cozy/cozy-libs#1503
> feat: Upgrade cozy-harvest-lib to 8.0.0

- CHANGELOG.md
- package.json
- yarn.lock
This is an upgrade of cozy-harvest-lib
> fix: Now show the jobs as running after first account configuration in Harvest

- src/components/Konnector.jsx
- src/components/Konnector.spec.jsx
History.push() is not good here, it will go back to /connected/:connectorName. Replace is better so we don't go back to the connector endlessly
> feat: Fix back navigation on konnector dismiss

- package.json
- yarn.lock
This version retrieves a fix that prevented cozy-harvest-lib's
AppLinkCard to work on react native
Related PR: cozy/cozy-libs#1529
> feat: Upgrade cozy-harvest-lib to 8.1.1

- src/components/Konnector.jsx
- src/components/Konnector.spec.jsx
A recent commit replaced the `push()` call with a `replace` call to fix a bug. This must be reverted to keep the going back to connector behavior when navigating backward.
With `history.push`, some environments will go back to the connector when going back through navigation. Firefox, Chrome, and Webview browser are not affected by the native UI of these environments. Broken environments can be mouse navigation or other more exotic navigation means which are not tested at this time.
Testing script:
```
window.onpopstate = function (event) {
console.log(event.path[0].location.href)
}
```
1. Click on a connector
- `http://home.cozy.localhost:8080/#/connected/alan`
- `http://home.cozy.localhost:8080/#/connected/alan/accounts/123`
2. Ask the browser to go back
- …
> fix: Use push on dismiss

- src/components/Konnector.jsx
When there is no `Konnector` prop, the application will crash (it can happen if Home App is opened directly on a konnector URL for instance).
This happens because no slug is passed to `Konnector` component.
In order to fix this, we can read the URL and get the slug from there.
As URLs are predictable, we can safely assume the slug will always be
the third string in the hash pathname.
> fix: Fallback to slug name in URL

- CHANGELOG.md
- package.json
- yarn.lock
We have a few warnings in the console because of this lib. Upgrading the lib fix them. 
Mostly this one: https://github.com/cozy/cozy-keys-lib/compare/v4.1.0...v4.1.1
> feat: Upgrade cozy-keys-lib

- CHANGELOG.md
- src/containers/App.jsx
If we came from the store, by clicking on "open" on a konnector,
we're redirected to the Home application with the /redirect path
Inside this redirect path, we render the IntentRedirect component.
This component reads the redux store to fetch the current installed
konnectors.
But since we were setting isFetching to false by default, we had, at the
first render, isReady to true. So we redirected to /redirected without
having the informations about the konnectors yet.
The fix is pretty simple. We need to check if at the first render, one
query is in loading state.
Also, I refactored to use `some` instead of `find` to only deal with
boolean.
> fix: Intent redirect

- src/components/Services.jsx
Realtime introduces konnector deletion. KonnectorTile should be linked to id, not random index
> fix(applications): KonnectorTile should be sorted according to their id

- CHANGELOG.md
- package.json
- yarn.lock
This version retrieves a feature that allow `cozy-client` to force
HTTPs on fetches if `window.cozy.isSecureProtocol` is `true` (which
should be the case when `cozy-home` is served from ReactNative)
Related PR: cozy/cozy-client#1172
> feat: Upgrade cozy-client to 28.3.0

- config/webpack.config.cozy-home.js
https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin
This plugin warned a lot in cozy-home because we used to have a lot of
duplicated packages. That's why dup packages are now set in webpack config.
Except date-fns that is still used in both version (4 issues).
After: only one warning of duplicated packages (date-fns):
> fix(deps): Specify use of node_modules packages for duplicate packages

- package.json
- yarn.lock
Previously it was black icons, now they should be white
> fix: Handle Amirale icons on UnlockVault

- .eslintrc.json
- jest.config.js
- package.json
- src/components/BackgroundContainer.tsx
- src/components/Konnector.jsx
- src/containers/App.jsx
- src/hooks/useOpenApp.spec.ts
- src/hooks/useOpenApp.ts
- src/styles/app.styl
- src/styles/backgroundContainer.styl
- src/styles/index.styl
- src/targets/browser/index.jsx
- tsconfig.json
- yarn.lock
Addresses this [ticket](https://trello.com/c/oxm6FGJG/455-%F0%9F%8E%81-e137-animation-%C3%A0-louverture-des-connecteurs-j).
`cozy-home` has to handle zoom-in/zoom-out animations on demand. This has to be compatible with **App Amirale** but nothing specific will be implemented for that in this PR. 
`cozy-harvest-lib` doesn't need to be upgraded to its latest version before merging, because it handles the fadeIn animation by itself, and `cozy-home` handles its animation alone.
Since we're dealing with CSS animations it is too cumbersome to write tests for it. Testing was only done manually.
**Test Configuration**:
* WSL2 (Ubuntu-20.04) on Windows 10 Pro
* Microsoft Edge (Official build)
> feat: Implement CSS transitions for apps/connectors open/exit

- CHANGELOG.md
- package.json
- yarn.lock
To get BI reconnection via webviews
> fix: Ugrade harvest to 9.8.0

- package.json
- src/styles/app.styl
- yarn.lock
The `<Dialog />` `cozy-ui` component used by *Harvest* has a flaw in its design
In small screens, it will display (probably by error) the modal title in a `padding: 12px 16px 16px 48px` setting
This is highly undesired and unfortunately we can't add class or any styling props to this part of `<Dialog />`
At the time of this commit, the simplest way to handle the issue is to override the `.dialogTitleWithBack` class
This way we can apply our desired design in a limited scope: only *Home*, only *Mobile*
Issue created [here](https://github.com/cozy/cozy-ui/issues/2165)
> fix: Improve spacing in Connector title block

- src/components/HeroHeader/index.jsx
- src/components/Shortcuts/ShortcutsView.jsx
- src/components/Shortcuts/ShortcutsView.spec.jsx
Added a nbsp in hero-title so it
does always have correct placeholder height
Deleted Spinner for shortcuts loading.
Displaying nothing instead
> fix: Cosmetic improvements

- package.json
- yarn.lock
3.11.1 seemed to have defects in the delivered package
> fix: Update cozy-keys-lib to 3.11.2

- src/components/MoveModal.jsx
It was believed that instanceSettings would at last be an empty object.
But an occurence can make it appear as undefined.
As a preventive measure, assume it can be undefined.
Then later we have to find out why it's undefined in the first place
> fix: Assume instanceSettings can be undefined

- src/styles/lists.styl
Adding a CSS property to make it transparent
instead of default Chrome blue
> fix: Remove chrome highlight on AppTile touch

- src/targets/browser/index.ejs
This should allow faster display of the custom fonts,
that way we don't have to fallback while waiting
> feat: Preload fonts before CSS is fetched

- package.json
- src/components/ShortcutLink.jsx
- src/components/Shortcuts/__snapshots__/ShortcutsView.spec.jsx.snap
- yarn.lock
We lose the ability to display the binary of a shortcut. Let's add it again.
Needs https://github.com/cozy/cozy-ui/pull/2190
> fix: Display IconBinary for shortcut

- package.json
- src/components/Konnector.jsx
- yarn.lock
In flagship app, if RealTime is not active on `cozy-home` and the app
asks `cozy-home` to display a newly installed connector, then the
connector wouldn't be present in the local state and so
`cozy-harvest-lib` would throw an error
With new implementation, we set `konnectorSlug` so `cozy-harvest-lib`
can retrieve the connector from `cozy-stack` if it is not present in
local state
Related PR: cozy/cozy-libs#1740
____
TODO:
> fix: Open connector even if not present in local state

- src/components/HeroHeader/HelpButton.tsx
- src/cozy-ui.d.ts
After review, the help button should open a new tab no matter the env.
Also added better typings blueprint for cozy-ui icons in def file.
> fix: Help button should target blank everywhere

- src/targets/browser/index.jsx
Since the popup/InAppBrowser will now be hidden on login success
with https://github.com/cozy/cozy-libs/pull/1786
See the equivalent PR in banks : https://github.com/cozy/cozy-banks/pull/2456
> feat: Add a centered spinner oauth redirection

- CHANGELOG.md
- package.json
- yarn.lock
Behind the harvest.bi.webview flag
> fix: Upgrade Harvest to hide BIContractActivationWindow when needed

- package.json
- yarn.lock
`cozy-keys-lib` as been upgraded to to `4.3.0` to retrieve a fix
that prevent crash when vault contains organizations with no key
Related PR: https://github.com/cozy/cozy-keys-lib/pull/204
___
`cozy-harvest-lib` as been upgraded to to `9.27.2` to retrieve a fix
that make it compatible with `cozy-keys-lib` version `4.1.0` and later
Related PR: https://github.com/cozy/cozy-libs/pull/1860
___
To test this:
- On cozy-pass, share a folder from Alice to Bob (Bob should not be trusted by Alice yet)
- On Bob's side, accept the sharing (but do not confirm Bob's identity on Alice's cozy-pass)
- On Bob's cozy-home, open a connector, configure it, fill the cozy-pass prompt and set a new password
- The action should success
> feat: Upgrade `cozy-keys-lib` to 4.3.0 and `cozy-harvest-lib` to 9.27.2 

- package.json
- yarn.lock
- To allow contract synchronisation to work
- To support upgrade to cozy-keys-lib v4 when no vault is setup
> feat: Upgrade cozy-harvest-lib to 9.29.5

- package.json
- src/components/Home.jsx
- yarn.lock
To get the new CozyConfirmDialogProvider which allows harvest to display a confirm dialog outside of its components tree.
> feat: Upgrade cozy-harvest-lib to 9.32.5

- package.json
- src/components/AnimatedWrapper.jsx
- src/containers/App.spec.jsx
- src/styles/backgroundContainer.styl
- yarn.lock
In #1730 we attempted to fix the background's position so it would not
show a white area on top of the app when trying to pull-to-refresh from
our Flagship app
This had 2 side effects
The first one is that pull-to-refresh was not possible anymore on iOS
Safari and also the address bar would not hide anymore when scrolling
To prevent this we chose to apply the custom CSS only when the app is
hosted by our Flagship app
The second side effect is that trying to trigger the pull-to-refresh
gesture would freeze the UI for a few seconds. This is a common issue
with `position: fixed` divs
To prevent this, we wrapped the `main` div with `<RemoveScroll />`
plugin that would completely lock the scroll of the HTML body and only
allow the `main` div to scroll. However the `position: fixed` is still …
> fix: Use `RemoveScroll` to prevent OS pull-to-refresh on Flagship app

- src/components/IntentRedirect.jsx
Query strings were mishandled, and the redirection could not happen.
These problems have been solved by using the right API to get the QS.
> fix: Update IntentRedirect for router6

- manifest.webapp
- src/targets/services/cliskTimeout.js
This service stops the given job with a 'context deadline exceeded' error. It may be called when
the execution of the clisk konnector is too long or when the flagship app has crashed.
The flagship app will also timeout the job if it restarts but this way, the user will not see
the job as running even outside the flagship app
This service is supposed to be called directly or via a @in or @at trigger
Example to call this service :
```javascript
await client.collection('io.cozy.jobs').create(
'service',
{
name: 'cliskTimeout',
slug: 'home',
fields: {
cliskJobId: '<the job id>'
}
}
)
```
```
* feat: Add cliskTimeout service
```
> feat: Add cliskTimeout service

- package.json
- src/components/AppWrapper.jsx
- src/components/AppWrapper.spec.jsx
- src/components/BackgroundContainer.tsx
- src/components/KonnectorTile.jsx
- src/components/Services.jsx
- src/cozy-ui.d.ts
- src/lib/konnectors_typed.ts
- src/store/configureStore.js
- tsconfig.json
- yarn.lock
```
* Konnectors under a running job will show their AppIcons in a loading state
* Fixed a typo that disabled Redux dev tools in local development
* Update cozy-client and cozy-stack-client to `^35.6.0`
```
> feat: Implement Konnector spinner

- package.json
- yarn.lock
To get the Wait for startLaucher resolution with clisk konnectors
```
* cozy-harvest-lib 13.8.0 : wait for startLauncher resolution with clisk konnectors [5f322b7a7](https://github.com/cozy/cozy-libs/commit/5f322b7a7534350d3251f597180a957339ef1129)
* Remove flag condition to display datacard ([89bffc4](https://github.com/cozy/cozy-libs/commit/89bffc45d0e51a25fa61372ec4191c29f5fcec81))
```
> feat: Upgrade Harvest 13.8.0

- .bundlemonrc
- package.json
- src/components/AddButton/ActionsBottomSheet.jsx
- src/components/AddButton/helpers.js
- src/components/AddButton/helpers.spec.js
- src/components/AddServiceTile.jsx
- src/components/CandidateCategoryTile.jsx
- src/components/FallbackCandidateServiceTile.jsx
- yarn.lock
```
* Disable creation of office document in mobile with the flag `drive.office.disableMobileEditing`
```
**Notes:**
Need to use the flag `drive.office` with `enabled: true` property inside to show the link to office creation
**Related PRs:**
- https://github.com/cozy/cozy-libs/pull/2065
> feat: Disable creation of office document in mobile

- src/queries.js
Like that we remove the warning:
```
cozy-stack-client warn Selector fields should be manually indexed to prevent unexpected behaviour
```
```
* Remove cozy-stack-client warning about indexFields
```
> fix: Define the indexFields for the magicfolder query

- src/store/configureStore.js
Added flag('home.store.persist') in order to persist store even in a browser.
ATM, this flag is used only for dev & debug purpose. Don't use it in production.
```
* We can persist the Home's store in the browser through the flag flag('home.store.persist')
```
> feat: Add flag to persist store even in the browser

- package.json
- yarn.lock
To allow harvest to receive LOGIN_SCCESS event from flagship app
```
* Get LOGIN_SUCCESS event from flagship app
* Display backdrop if the error needs an action from the user
* Make konnector prop mandatory to FlowProvider
```
> feat: Upgrade cozy-harvest-lib to 13.12.0

- package.json
- yarn.lock
This will fix a bug in Harvest fileviewer,
where shown files would be the wrong ones in the vast majority
of cases.
> fix: update cozy-harvest-lib

- src/components/BackgroundContainer.tsx
- src/global.d.ts
- src/targets/browser/index.ejs
- src/targets/browser/index.jsx
- src/targets/browser/index.test.jsx
- src/targets/browser/renderApp.tsx
- tsconfig.json
The app was always rendered twice in a row with a 30ms interval
This was because renderApp() was called twice with bad
HMR handling.
HMR update has been disabled for now because it doesn't work correctly.
The whole page will reload just as before when a file is updated.
This will  be fixed in another commit
This will also fix a bug in react-native WebView where the
static assets are never updated.
With the cache busting in dev mode only,
the webview will refetch the files everytime
> fix: improve workflow for native app

- package.json
- yarn.lock
To fix:
- Non updated harvest when loginSuccess is too fast
- Recursive error on multiple account creations
- oauth account creation
```
* Non updated harvest when loginSuccess is too fast
* Recursive error on multiple account creations
* oauth account creation
```
> fix: Ugrade harvest to 13.14.5

- src/ducks/connections/index.js
This will check if the input date string is in the extended ISO 8601 format
and trims the fractional seconds part to 6 digits if it has more than 6 digits.
This is done to avoid deprecation warnings from Moment.js regarding
non-standard date formats, as Moment.js expects a maximum of 6 digits for
fractional seconds in the ISO 8601 format.
> fix: convert date before getting lastSync

- src/components/AppTile.jsx
- src/components/AppTile.spec.jsx
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/it.json
- src/locales/ja.json
- src/locales/nl_NL.json
- src/queries.js
The AppTile component was not correctly updating when an app's state changed from `'installing'` to `'ready'`. This resulted in the app icon staying as a placeholder forever in persistent scenarios (native).
To resolve this issue, we introduced a new wrapper component, `AppTileWrapper`, responsible for managing the app's state and fetching the app's information when the state changes from `'installing'` to `'ready'`. The `AppTileWrapper `component utilizes a `useEffect` hook to detect the change in the app's state and fetch the updated app information accordingly.
When the app's information is unavailable (i.e., the app is in the `'installing'` state), `AppTileWrapper` renders a loading icon using the `SquareAppIcon` component. Once the app's state changes to `'ready'` and the information …
> fix: improve app creation realtime management

- package.json
- yarn.lock
To avoid FlowProvider reload on trigger launch
```
* Avoid FlowProvider reload on trigger launch
```
> feat: Upgrade cozy-harvest-lib to 3.17.3

- .bundlemonrc
- package.json
- src/components/AddButton/AddButton.jsx
- src/components/AppWrapper.jsx
- src/components/AppWrapper.spec.jsx
- src/components/Applications.jsx
- src/components/BackgroundContainer.tsx
- src/components/HeroHeader/CornerButton.jsx
- src/components/HeroHeader/index.jsx
- src/components/Konnector.jsx
- src/components/KonnectorErrors.jsx
- src/components/Shortcuts/ShortcutsView.jsx
- src/components/Shortcuts/__snapshots__/ShortcutsView.spec.jsx.snap
- src/hooks/usePreferedTheme.ts
- src/styles/app.styl
- src/styles/backgroundContainer.styl
- src/styles/hero-header.styl
- yarn.lock
We want our partners to be able to chose there preferred theme (normal or inverted)
To allow this we add support to a `--home-theme` CSS variable that can be declared on the custom CSS from dynamic assets
When present, we apply this value into the application's wide theme
But there is an exception: if the user added a custom wallpaper to their cozy, then we enforce an inverted theme for better contrast
We also want our partners to be able to have more control on the displayed background
In combination with the new `--home-theme` variable a partner can customize the Cozy's background by targeting
`home-default-partner-background` css class on the custom CSS from dynamic assets. However this can only be done when choosing the `normal` theme
To ease background customization, the background's …
> feat: Add theme and complex background support to cozy-home  

- src/components/HeroHeader/SettingsButton.jsx
The SettingsButton was never displayed because the `settingsAppQuery` query would return the app object instead of an array
Related commit: 6e59f08f8dc55f6bedb888e22acde49ce275169a
> fix: Make SettingsButton work again

- src/hooks/usePreferedTheme.ts
In some environments `getComputedStyle().getPropertyValue()` would return a result with a leading space
In this scenario we retrieve ` normal` instead of `normal`
So we want to `trim()` the result
Note that `getComputedStyle().getPropertyValue()` always return a string even if the property does not exist. In that cas the string is empty. So we don't need to check for nullity
> **Note**
> This commit is a cherry pick from a fix done in the release branch and is a fix for https://github.com/cozy/cozy-home/pull/1939 also included in the 1.52.0 release
> Therefore this PR has no release note
> fix: Use `trim()` on `usePreferedTheme`

- src/components/BackgroundContainer.tsx
For one of our partners customizations we want an animated background
This background animation need some supplementary divs so we can do it in CSS
Those divs are empty and contains no classes so they won't impact generic Cozies
But we can easily target them in a custom Theme CSS stylesheet by targeting `.home-default-partner-background div:nth-child(n)`
```
* Improve UI customization capabilities for our partners
```
> feat: Add some empty div in BackgroundContainer to allow customizations

- src/components/HeroHeader/LogoutModal.tsx
- src/cozy-ui.d.ts
Cozy Home can have normal or inverted theme now,
so we need to specify the theme we want when we
open a modal.
In this case, let's force the Normal theme.
```
* Logout modal on flagship app now have the right color
```
> fix: Normal theme for Logout Modal

- src/containers/IntentHandler.jsx
Since the Home can be inverted / normal, we have to force the theme we want when opening an intent / modal.
Here, this intent is mainly used by the Store App so let's use the Normal theme.
```
* Intent: Konnector configuration from the Store is well displayed with the right theme
```
> fix: Set the CozyTheme to the intent

- src/containers/App.jsx
- src/containers/ReloadFocus.jsx
Since we heavily rely on relatime to update the redux store, we can miss a message when the app is in background or else. It can result to open Harvest with outdated information and it will then display an error.
Here, we refresh triggers, accounts and konnectors when the focus is there.
This code will be removed once the migration to cozy-client is done.
> feat: Reload data on focus

- src/containers/App.jsx
When the Home is ready and asks for a hide splashscreen,
We will now also send the value of the preferred theme
to the native app,
so it can handle OS icon color in a better way.
> feat: send home theme to webview when ready

- package.json
- src/components/AppTile.jsx
- src/components/AppWrapper.jsx
- src/components/KonnectorInstall.jsx
- yarn.lock
```
* Define the maximum number of accounts allowed to connect using konnectors with the flag `harvest.accounts: {"max": 10, "maxByKonnector": {"default": 3}`
* Update cozy-flag from 2.12.0 to 3.0.1
* Update cozy-harvest from 13.20.0 to 14.0.0
```
**Related PRs:** 
* https://github.com/cozy/cozy-ui/pull/2452
* https://github.com/cozy/cozy-libs/pull/2190
> feat: Define the maximum number of accounts allowed to connect using konnectors

- package.json
- yarn.lock
To allow powens konnectors to reconnect
```
* Display reconnection webview for powens konnectors ([a924d3e](https://github.com/cozy/cozy-libs/commit/a924d3e13524f211bc8ae45435a012b8e2125ed8))
```
> feat: Upgrade cozy-harvest-lib to 14.1.0

- package.json
- yarn.lock
Upgrade harvest to 14.1.1
```
* Do not display reconnection webview for USER_ACTION_NEEDED state
* Show accounts paywall for oAuth konnector
*
*
```
> fix: Do not display reconnect webview on actionNeeded error

- src/components/FallbackCandidateServiceTile.jsx
If there is no registry data it is better to render nothing
because we won't have any link to the Konnector,
despite having its slug.
This is because failing to get the data most likely means
that the Service is not available
on the current registry (404 Not Found).
It is not a problem if the Service is not available on the registry,
but it is a problem if we try to link to it.
Here it would display an AppLinker with a grey cube,
an unformatted slug as a name and no working link.
> fix: render null if konnector not in registry

- manifest.webapp
I removed this route recently, but this route is used just after a creation of a cozy...
> fix: Add /intro route

- src/components/AppTile.jsx
- src/components/AppTile.spec.jsx
Apps can have an "upgrading" state and not just an "installing" one. In that case, we want to display the "Loading" tile, but then once the process is
done, we want to display the real tile and remove
the loading one.
```
* Loading App tile should not be "persisted" anymore. It should only be displayed a few seconds if needed.
```
> fix: Handle upgrading apps

- src/components/ShortcutLink.jsx
```
* We only need this call to useFetchShortcut in order to get the URL of the shortcut. For the rest of the information like the icon or iconType, we already have the informations within the file. So let's use these informations instead of waiting an http request to resolve.
```
> fix: Optimization to display the Shortcut icon

- src/config/home.json
The home shortcuts are configured in the /Settings/Home folder, and we've done the same for the wallpapers
```
* Change your wallpaper by adding a Wallpaper.jpg into the folder `/Settings/Home` in Drive
```
> feat: Group wallpaper configuration in home settings

- src/components/BackgroundContainer.tsx
- src/containers/App.jsx
- src/cozy-ui.d.ts
By reading the theme value, we call the API only twice. We can go further and only call once, maybe I'll do it later if I've enough time.
```
* Optim:  Don't call 4 times /download/Wallpaper. Call it only twice
```
> fix: Don't call /download/Wallpaper 4 times

- src/components/AppHighlightAlert/AppHighlightAlertWrapper.jsx
- src/components/AppHighlightAlert/BackupAppHighlightAlert.jsx
- src/components/AppHighlightAlert/GeolocationTrackingAppHighlightAlert.jsx
- src/components/Applications.jsx
- src/locales/en.json
- src/locales/fr.json
```
* Add a pointer alert to present geolocation tracking feature
* Manage multiple alerts
```
> Add an AppHighlightAlert targeting coachco2

- src/components/AppHighlightAlert/AppHighlightAlert.jsx
- src/components/Applications.jsx
- src/styles/lists.styl
I had to play with margin-bottom on AppHighlightAlert and grid-gap to counterbalance the removal of auto-fit.
```
* Allow long text in AppHighlightAlert
```
> feat: Allow long text in AppHighlightAlert

- src/components/AppHighlightAlert/GeolocationTrackingAppHighlightAlert.jsx
- src/locales/en.json
- src/locales/fr.json
```
* Display coachco2 CTA in web
```
> Display coachco2 CTA in web and rename flag attributes

- package.json
- yarn.lock
```
* Allow to skip maintenance for konnector with `harvest.skip-maintenance-for` flag
* Update cozy-harvest-lib from 20.1.6 to 20.2.0
```
> feat: Update cozy-harvest-lib from 20.1.6 to 20.2.0

- src/components/DefaultRedirectionSnackbar/DefaultRedirectionSnackbar.jsx
```
* Correct the position of the snackbar to change the default application in the Flagship
```
> fix: DefaultAppSnackbar position in the Flagship

- src/components/AppHighlightAlert/GeolocationTrackingAppHighlightAlert.jsx
Condition was inverted.
```
* Display coachco2 CTA if no data in coachco2 like it is supposed to
```
> fix: Display coachco2 CTA if no data in coachco2 like it is supposed to

- package.json
- src/components/Shortcuts/__snapshots__/ShortcutsView.spec.jsx.snap
- yarn.lock
This update allows us to anticipate the arrival of IAP in the paywall.
```
* Update cozy-ui from 98.1.1 to 100.0.0
* Update cozy-client from 45.0.1 to 45.1.0
```
> Update cozy-ui from 98.1.1 to 100.0.0

- src/components/AppHighlightAlert/AppHighlightAlertWrapper.jsx
- src/components/AppHighlightAlert/BackupAppHighlightAlert.jsx
- src/components/AppHighlightAlert/GeolocationTrackingAppHighlightAlert.jsx
- src/components/AppHighlightAlert/helpers.js
- src/components/AppHighlightAlert/helpers.spec.js
```
* App highlight alert could never show if related app was not installed
```
> App highlight alert could never show if related app was not installed

- .travis.yml
Travis is configured to run on branches and PRs. The problem is that the CI is triggered at force push for all branches even if there is no associated PR, and for those with PRs the CI is therefore triggered twice.
> chore: Don't run CI for branches if not master

- src/targets/services/myselfFromIdenties.js
By not using it, we dont enforce cozyMetadata.
So let's use CozyClient.save() to have these
cozyMetadata.
```
*
* Add cozyMetadata to myself when created from the mySelfFromIdentities' service
*
```
> fix: Use client.save() to create / mutate data

- package.json
- yarn.lock
In order to have fully functionnal flow for a konnector installation and configuration from the store.
> fix: Upgrade harvest to get IntentProvider

- config/webpack.config.cozy-home.js
- docs/develop.md
- src/containers/App.jsx
- src/targets/browser/index.ejs
Like that, no need to be in the flagship env to test the behavior on the web.
> feat: Simulate a call to hidesplashscreen on the web

- src/targets/intents/index.ejs
I imported the fonts, but not the css file to be able to use them
> fix: Import fonts.css

- package.json
- src/components/AppWrapper.jsx
- src/components/AppWrapper.spec.jsx
- src/components/BackgroundContainer.tsx
- src/containers/App.spec.jsx
- src/hooks/useCustomWallpaper.jsx
- src/hooks/useCustomWallpaperContext.tsx
- src/hooks/usePreferedTheme.ts
- yarn.lock
We already reduce the number of request to wallpaper, but here we go further and make only one call (see https://github.com/cozy/cozy-home/pull/2020 for the first iteration).
Also, we store 2 things :
- within the localStorage : the fact that we have a custom wallpaper or not, in order to have a quick path to know what to do
- within the localforage, the binary of the wallpaper. I decided to store it within localforage, because localstorage has a limite to 5 or 10MB depending on the browser. And since a wallpaper can be huge... like that "no limit".
Maybe the next iteration will be to call "hidesplashscreen" only if the wallpaper is fully loaded.
```
* Store the binary of the customwallpaper in the localStorage
* Call only once the API to get the wallpaper (instead of 2 times) 
```
> feat: Add a context to store the custom Wallpaper

- src/hooks/usePreferedTheme.ts
Since 5c850137f7a26fa1b35576408cf93f5cfbc4f01e I store the default wallpaper into the wallpaperlink var of the hook.
But I didn't expect that an other hook was relying on this value to determine if it was an inverted theme or not.
So I fix the issue by checking if the current wallpaper is different of the default one.
> fix: Home Style

- src/components/Shortcuts/utils.js
- src/components/Shortcuts/utils.spec.js
We didn't call hidesplashscreen when a cozy didn't have shortcuts. This was because we didn't check correctly the fact that the data has been loaded or not.
Now we're less naive that the first implementation
> fix: Fix isready status

- src/store/configureStore.js
The idea of the migration is to reset the already persisted data because a lot of stuff has been added in it.
Like that, we start with fresh data.
> fix: Upgrade Persisted Store Version

- src/containers/App.jsx
In a previous attempt fda23d869ecd63ef6805ec171d911c78ee9d3928 I managed to try to fix the call to hideSplashScreen.
I fixed the call when the user had a magicFolder but without custom shortcuts. But missed the case where the user doesn't have a magic folder.
This is a TMP fix. I need to think about a better fix and mainly a way to add a few UT to that method.
> fix: Call isReady

- manifest.webapp
- package.json
- yarn.lock
Upgrade cozy-harvest-lib to 22.3.0 to get :
- to get cozy doctypes debug view
- to get UNKNOWN_ERROR.PARTIAL_SYNC error translation
Upgrade cozy-client to 45.8.0 to get:
- client.models.account.getAccountLogin use manifest identifier
attribute when available
- feat: Add io.cozy.bills and io.cozy.identities permissions
```
* cozy doctypes debug view
* UNKNOWN_ERROR.PARTIAL_SYNC error translations
```
> [SCR-114] feat: Upgrade cozy-harvest-lib and cozy-client

- package.json
- yarn.lock
To get the correct sourceAccountIdentifier from clisk account
This will allow clisk imported documents to be display in harvest debug
cards.
```
* Display documents imported by clisk konnectors (correct sourceAccountIdentifier)
```
> [SCR-114] fix: Upgrade cozy-harvest-lib to 22.4.1

- package.json
- src/components/BackgroundContainer.tsx
- src/components/HeroHeader/CornerButton.jsx
- src/components/HeroHeader/index.jsx
- src/components/Services.spec.jsx
- src/components/Shortcuts/__snapshots__/ShortcutsView.spec.jsx.snap
- src/containers/App.jsx
- src/cozy-ui.d.ts
- src/targets/browser/index.ejs
- src/targets/intents/index.ejs
- yarn.lock
`cozy-ui` has been upgraded to `103.6.2` to retrieve the new Theme variants support (light and dark)
The code changes are for handling the `cozy-ui 101.0.0` breaking changes
One of the changes consist to force the light theme as there are no specs yet for this theme support on cozy-home
Related PR: cozy/cozy-ui#2540
```
* 
*
* Upgrade cozy-ui to latest (103.6.2)
```
> [VO-427] feat: Upgrade cozy-ui cozy-ui to 103.6.2

- manifest.webapp
- src/targets/services/sourceAccountIdentifierNormalizer.js
- src/targets/services/sourceAccountIdentifierNormalizer.spec.js
This service will normalize the cozyMetadata.sourceAccountIdentifier
attribute in io.cozy.identities,io.cozy.bills,io.cozy.accounts doctypes.
This attribute is needed for debugging purpose for identities and bills
and having this directly specified in accounts without needing any
algorithm is easier to use.
This service must be run manually at the moment since we don't want tu
run it multiple times for every konnector which updates all these
doctypes at one and I did not find a way to specify a unique @event trigger
for multiple doctypes.
```
* Add sourceAccountIdentifierNormalizer service
```
> [SCR-346] feat: Add sourceAccountNormalizer service

- .travis.yml
- src/components/appEntryPoint.jsx
- src/containers/ReloadFocus.jsx
When focusing the home, we make a query to update data. We had a wrong query definition which couldn't be handle by [sift](https://github.com/crcn/sift.js) as it requires MongoDB operators. This query overwrites the results of previous queries on the doctype `io.cozy.triggers`. When the paywall was checked, it was found that the user had no account.
```
* Show account paywall even after focus
* Make unit test in node 20
```
> [VO-524 & VO-486] fix: Show account paywall even after focus

- src/targets/services/sourceAccountIdentifierNormalizer.js
- src/targets/services/sourceAccountIdentifierNormalizerHelper.js
- src/targets/services/sourceAccountIdentifierNormalizerHelper.spec.js
Protect sourceAccountIdentifierNormalizer service against references to non-existing files as invoice in bills (when the user removes the files himself
- fix: Make the service job fail on errors
```
* sourceAccountIdentifierNormalizer service: handle bills with non existing invoice files
* sourceAccountIdentifierNormalizer service: script error now make the service fail
```
> [SCR-442] fix: Do not fail service on non existing invoice files

- package.json
- yarn.lock
To have the Can't connect link hidden when a konnector does not have any vendor_link in the manifest
```
* Hide the Can't connect link when no vendor_link is available in the konnector manifeste
```
> feat: Upgrade cozy-harvest-lib to 22.5.11 (SCR-528)

- package.json
- yarn.lock
To avoid to propose all ciphers when a konnector does not have
any vendor_link in its manifest
```
* Do not propose all ciphers when a konnector does not have any vendor_link
```
> fix: Upgrade harvest to 23.0.0 (SCR-531)

- package.json
- yarn.lock
To transmit correct account identifiers on reconnect
https://github.com/cozy/cozy-libs/pull/2528
```
* transmit correct account identifiers on reconnect [PR](https://github.com/cozy/cozy-libs/pull/2528)
```
> fix: Upgrade harvest to 23.0.1 (SCR-508)

- src/targets/browser/index.ejs
- src/targets/intents/index.ejs
because of `mix-blend-mode multiply` on .App, there is a conflict that causes a black veil to appear on the application on Chrome
> fix: Remove color-scheme and use default value

- src/targets/browser/index.ejs
- src/targets/intents/index.ejs
This reverts commit b715268c93eef989f262ed794c25ceda748091db.
Since we removed `mix-blend-mode multiply` on .App
> fix: Readd color-scheme

- src/styles/app.styl
We use a combination of backdrop-filter and mix-blend-mode to darken the background image. However, this take into account the background color of the body which is white in light mode and a strong gray in dark mode.
So here we override the background color in .App to white. It has no effect on the container using .App, but it avoid mix-blend-mode to be linked to the background color of the body.
```
*
* Background was too dark in dark mode
*
```
> fix: Avoid to make the background image too dark in dark mode

- package.json
- src/components/AppWrapper.jsx
- src/components/AppWrapper.spec.jsx
- src/components/ShortcutLink.spec.jsx
- src/components/Shortcuts/__snapshots__/ShortcutsView.spec.jsx.snap
- test/AppLike.jsx
- yarn.lock
To better support dark mode (flagship app and dark mode button in cozy-settings).
```
*
*
* Update cozy-ui to 110.1.0 (better dark mode support)
```
> feat: Update cozy-ui to 110.1.0

- src/components/Sections/SectionDialog.tsx
- src/cozy-ui.d.ts
- src/styles/lists.styl
Using px value was unfit for small screens;
Instead, using fullWidth prop from material-ui.
This does not make the component take all the screen, just the full width available to it.
https://v4.mui.com/api/dialog/
> fix: use `fullWidth`  to handle  minWidth VO-892

- package.json
- yarn.lock
A change in cozy-ui did not make this button as "submit" type by default
anymore.
```
* Submit 2FA on 2FA submit button click (cozy-harvest-lib 27.0.0 -> 27.0.1)
```
> fix: Submit 2FA on 2FA submit button click (SCR-777)

- src/components/KonnectorTile.jsx
- src/components/Sections/SectionView.tsx
Made naming clearer about what it does
Also removed the logic that would consider a suggested
konnector (from doctype) the same as a suggested konnector
(from front-end point of view).
So now when opening a suggested konnector that is also not connected,
we are not redirected to the store.
> fix: remove isSuggestion check in sectionview

- src/styles/lists.styl
Use minmax instead of full
both desktop and mobile
> fix: handle long detailed items in grid VO-959

- src/components/Sections/lib/formatServicesSections.ts
Item in maintenance and installed: display
Item in maintenance not installed: do not display
Item in maintenance in pristine category: do not display
> fix: show items in maintenance if installed VO-949

- src/components/Announcements/Announcements.tsx
- src/components/Announcements/AnnouncementsDialog.tsx
- src/components/Announcements/AnnouncementsDialogContent.tsx
- src/hooks/useAnnouncements.tsx
- src/hooks/useAnnouncementsSettings.tsx
**List of change onto announcements :** 
- Change the way seen works
- Limit the number of announcement displayed simultaneously to 5
- Show announcements only 1h after the first time the feature is activated
There is more context into each commit message
> [VO-1064 & VO-1067] feat: Take into account feedback on announcements

- src/components/ShortcutLink.jsx
This RP adapts the data format of shortcuts once their metadata has been standardised ([PR on cozy-doctypes](https://github.com/cozy/cozy-doctypes/pull/268)).
**Related PRs :**
- https://github.com/konnectors/toutatice/pull/482
> [VO-1073] fix: Adapts the data format for shortcuts

- src/components/ShortcutLink.jsx
This reverts commit 07109a638bc4dacc8f218ba85a805f1866658bac. There are existing shortcuts that rely on `metadata.description`. Therefore, we revert this change.
```
*
* Use `metadata.description` rather than `metadata.target.description`
*
```
> Revert "fix: Change shortcut metadata format"

- src/assistant/AssistantDialog.jsx
- src/assistant/Conversations/ConversationSearchBar.jsx
- src/assistant/ResultMenu/ResultMenu.jsx
- src/assistant/ResultMenu/ResultMenuContent.jsx
Ce n'est pas une solution idéale, mais dans le temps imparti c'est la solution retenue. On modifie également l'Ui pour mettre l'input en haut de l'écran dû à un comportement forcé de l'affichage du clavier sur iOS cf https://martijnhols.nl/gists/how-to-detect-the-on-screen-keyboard-in-ios-safari
Cette partie sera totalement retravaillée dans un second temps très prochainement. Nous sommes encore au stade du prototype...
> feat(Assistant): Replace search result bottomsheet in mobile by modal

- package.json
- src/assistant/AssistantProvider.jsx
- src/assistant/queries.js
- yarn.lock
```
* Assistant : Ignore instant messages if not for the actual conversation
```
> feat(Assistant): Ignore instant messages if not for the actual conversation

- src/assistant/Search/getIconForSearchResult.js
Since the search engine now uses a local PouchDB, the documents are not JSON-API compliant, so we should rely on `_type` instead of `type`
With previous implementation, we failed to compute icon for cozy-apps due to missing `doc.type` attribute, and returned the `unknown` type. This type was not handled by the `<ResultMenuItem>` item and the application would crash
This PR fixes the usage of the `_type` attribute but also return a default icon instead of `unknown` to prevent future crashes
> fix: Make the search work for cozy-apps again

- src/assistant/ResultMenu/ResultMenuContent.jsx
- src/assistant/Search/SearchBar.jsx
- src/assistant/Views/SearchDialog.jsx
- src/components/Home.jsx
- src/containers/App.jsx
- src/dataproxy/DataProxyProvider.jsx
Permet d'apporter un peu plus de granularité dans la gestion des fonctionnalités
`cozy.searchbar.enabled`: Affiche la barre de recherche (uniquement desktop/mobile web)
`cozy.searchbar.enabled-for-flagship`: Affiche la barre de recherche (uniquement flagship app)
`cozy.search.enabled`: Active la fonction de recherche
`cozy.assistant.enabled`: Active la fonctionnalité "Cozy Assistant"
> Assistant: Change flags name

- src/components/Announcements/AnnouncementsDialogContent.tsx
- src/components/Announcements/styles.styl
This PR changes the Announcements' bullet points style so they are aligned on the left
This is a quick PR to fix the style with a short deadline, we may want in the future to change the way the style is implemented (maybe on cozy-ui side?)
```
*
* Align announcements' bullet points on left side
*
```
> fix: Align announcements' bullet points on left side

- src/assistant/ResultMenu/styles.styl
and suggest scrolling, which is particularly useful on mobile because scrollbars are hidden
> feat(Assistant): Adjust result menu height to cut the last element

- src/assistant/AssistantWrapperDesktop.jsx
- src/assistant/AssistantWrapperMobile.jsx
- src/assistant/Views/AssistantDialog.jsx
- src/assistant/Views/SearchDialog.jsx
To override "inverted" variant when a custom wallpaper is set
```
* Fix search bar and assistant background color
```
> feat(Assistant): Force "normal" variant for searchbar and dialogs

- src/assistant/Conversations/ChatConversation.jsx
- src/assistant/Conversations/Sources/Sources.jsx
```
* We want to scroll down to the sources button when it is displayed
* We wasn't scrolling to the end of the instant message
```
> fix(Assistant): We wasn't scrolling to the end of the instant message

- src/assistant/ResultMenu/ResultMenuContent.jsx
- src/assistant/ResultMenu/ResultMenuItem.jsx
- src/assistant/ResultMenu/SuggestionItemTextSecondary.jsx
- src/assistant/ResultMenu/styles.styl
- src/assistant/Search/useFetchResult.jsx
See also https://github.com/cozy/cozy-libs/pull/2615
```
* [feat: Allow click on searched file's path](https://github.com/cozy/cozy-home/commit/a69397f6e77675a3c837f2dcfbd835e0eaec0afe)
*
*
```
> [PRD-610] feat: Allow click on searched file's path

- package.json
- src/components/Sections/actions/groupModeAction.tsx
- src/components/ShortcutLink.jsx
- src/components/Shortcuts/utils.js
- src/components/Shortcuts/utils.spec.js
- yarn.lock
```
*  Hide shortcut badge when for some context with `hide_shortcut_badge_on_home`
```
**Related PRs:**
- https://github.com/cozy/cozy-ui/pull/2717
> [VO-1194] feat: Hide shortcut badge when for some context

- src/components/Applications.jsx
The new flag `apps.hidden` replaces `home_hidden_flag` and will be also used in cozy-store and cozy-bar
```
* Replace `home_hidden_flag` by more generic `apps.hidden`
*
*
```
> [PRD-538] feat: Hide apps by flag

- src/dataproxy/DataProxyProvider.jsx
When running inside of Flagship app, we don't want to load the DataProxy's iframe
Instead we want to use the Flagship app's API
For now this API does not exist, so we just disable the DataProxy feature
We could have enabled the iframe until the native API is implemented, but for now this would introduce an infinite nested iframes bug as the Flagship app's WebViews intercept all requests to `/` or `/index.html` and inject the cozy-home code
```
*
* Disable DataProxy in Flagship app
*
```
> fix: Disable DataProxy's iframe when running inside of Flagship app

- package.json
- src/components/Konnector.jsx
- src/components/Konnector.spec.jsx
- src/containers/App.spec.jsx
- src/targets/intents/KonnectorRoutes.jsx
- src/targets/intents/index.jsx
- yarn.lock
```
* Update cozy-harvest-lib from 30.6.4 to 31.0.0
```
**Related PRs:**
- https://github.com/cozy/cozy-libs/pull/2627
> [VO-1184] feat: Update cozy-harvest-lib from 30.6.4 to 31.0.0

- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/it.json
Collect is an old name not used anymore
```
* Remove Cozy Collect mentions
*
*
```
> [VO-544] feat: Rename Collect in Home

- package.json
- src/components/AppHighlightAlert/AppHighlightAlertWrapper.jsx
- src/components/AppWrapper.jsx
- yarn.lock
```
* Make search working on flagship app
* Prevent infinite loop at startup when query fails
*
```
> Make search working on flagship

- src/containers/ReloadFocus.jsx
At each new focus, a full render was triggered, making a visual reload for the user.
To fix this, we do not use query options in the ReloadFocus component, because of: https://github.com/cozy/cozy-client/issues/931 Especially for the apps query, the fetchPolicy is always applied here, because it is called elsewhere, making the query's lastUpdate very close in time. And because of this, the home is rendered after each focus, as the same query gives different result (a complete response, vs an early empty return in this case)
```
*
* Do not reload home at focus
*
```
> fix: Avoid rendering at focus

- src/components/Sections/GroupedSectionsView.tsx
- src/components/Sections/SectionView.tsx
- src/components/Services.jsx
- src/components/Shortcuts/ShortcutsView.jsx
- src/components/Shortcuts/__snapshots__/ShortcutsView.spec.jsx.snap
During Twake migration to fit new UI requirements :
- first we modified shortcuts-list and services-list to reduce spacing
- but then we allowed to completely remove these lists with a flag `home.apps.only-one-list` to display apps, shortcuts and services in only one list
So the previous spacing reduction is not useful anymore for Twake UI and on the contraty breaks spacing when using the
`home.detailed-sections-dev` flag and `home.detailed-services-dev` flag
> fix: Correct spacing for shortcuts list

- src/components/BackgroundContainer.tsx
- src/hooks/useDefaultWallpaper.tsx
- test/AppLike.jsx
Because we use `import from` notation for the default wallpaper's svg the result is a relative URL
On the Flagship app, the relative URL won't work on some iOS devices due to Webview that uses unsecure `http`. On those devices, the svg file would not load (however this works on some iOS devices but we don't know why)
By generating an absolute URL using the Cozy instance's URL, we ensure that secure `https` will be use instead
> fix: Enforce absolute URL for default wallpaper

- package.json
- yarn.lock
The DataProxyProvider is now rendering children in any case
> fix: Avoid empty screen if dataproxy is unavailable

- package.json
- yarn.lock
This reverts commit 5600b448a6e4fb617366e72bb21ba9412c5ffd2f.
> Revert "feat: Upgrade cozy-dataproxy-lib for more defensive Provider"
